# Top Rated Coffee Dataset Wrangled

# Table of Contents — Top Rated Coffee Dataset Wrangled

1. Imports & Pathways    
2. Data Inspection  
3. Data Wrangle – Roaster Location  
4. Data Wrangle – Coffee Origin  
5. Wrangle Region
6. Wrangle Coffee Region
7. Wrangle Roaster Region
8. Export

## 1. Imports/Pathways

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os
import re

In [2]:
# File Pathway
path = r"C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee"

In [3]:
# Import dataset
df_coffee_wrangle = pd.read_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Top Rated Coffee\top_rated_coffee_clean.csv')

## 2. Data Inspection

In [4]:
df_coffee_wrangle.head()

,coffee_name,total_score,roaster_location,coffee_origin,roast_level,agtron_roast,price_usd,quantity_g,usd_per_gram
0,Colombia Finca Campo Hermosa,94.0,"Cleveland, Tennessee","Quindio Department, Colombia",Light,82.0,29.99,226.8,$29.99 / 226.8g
1,Colombia Finca La Sirena Mango Co-Ferment,94.0,"Cleveland, Tennessee","Quindio Department, Colombia",Light,87.0,22.99,226.8,$22.99 / 226.8g
2,In Bloom,94.0,"Jersey City, New Jersey",Colombia; Ethiopia,Light,88.0,25.00,250.0,$25.0 / 250.0g
3,Ethiopia Washed Kaffa Gimbo Lot Rich Espresso,96.0,"Chia-Yi, Taiwan","Gimbo, Kaffa Province, Ethiopia",Medium Light,77.0,8.17,226.8,$8.17 / 226.8g
4,Ethiopia Natural Gute Bona,95.0,"Chia-Yi, Taiwan","Sidamo growing region, southern Ethiopia",Medium Light,78.0,13.07,226.8,$13.07 / 226.8g

## 3. Data Wrangle - Roaster Location

In [5]:
# Temporarily expand row display limit
pd.set_option('display.max_rows', None)

# Show all unique locations
pd.DataFrame({'roaster_location': sorted(df_coffee_wrangle['roaster_location'].dropna().unique())})

                           roaster_location
0                      Acton, Massachusetts
1                   Albuquerque, New Mexico
2                         Anchorage, Alaska
3                       Annapolis, Maryland
4                          Anoka, Minnesota
5              Antigua Guatemala, Guatemala
6                        Antigua, Guatemala
7                        Arcata, California
8                  Arlington, Massachusetts
9                           Ashland, Oregon
10                         Atlanta, Georgia
11                            Austin, Texas
12                      Baronett, Wisconsin
13                     Barronett, Wisconsin
14                   Bedford, New Hampshire
15                   Bellingham, Washington
16                       Belmar, New Jersey
17                     Berkeley, California
18                    Berlin, Massachusetts
19                   Beverly, Massachusetts
20                         Big Lake, Alaska
21                        Billings, Montana
22                       Billings, Montana.
23                         Bogota, Colombia
24                    Boston, Massachusetts
25                        Boulder, Colorado
26                         Bozeman, Montana
27                     Branford Connecticut
28                    Branford, Connecticut
29                       Brooklyn, New York
30                        Buffalo, New York
31                      Burlington, Vermont
32                 Calgary, Alberta, Canada
33                      Cambria, California
34                   Caotun, Nantou, Taiwan
35                     Captain Cook, Hawaii
36                    Captain Cook, Hawai’i
37                     Carbondale, Colorado
38                     Carlsbad, California
39                  Changhua County, Taiwan
40                         Changhua, Taiwan
41                Charlotte, North Carolina
42                Charlottesville, Virginia
43                     Chia-Yi City, Taiwan
44                          Chia-Yi, Taiwan
45                        Chicago, Illinois
46                        Chino, California
47                         Chiya-Yi, Taiwan
48                     Cleveland, Tennessee
49                           Columbus, Ohio
50                         Conway, Arkansas
51                   Crystal Lake, Illinois
52                     Daejeon, South Korea
53          Dali District, Taichung, Taiwan
54                            Dallas, Texas
55                         Denver, Colorado
56                         Des Moines, Iowa
57                     Douliou City, Taiwan
58                     Driftless, Wisconsin
59                        Duluth, Minnesota
60                        Durango, Colorado
61                   Durham, North Carolina
62                   Emeryville, California
63                           Eugene, Oregon
64                      Everett, Washington
65                          Floyd, Virginia
66                   Fort Bragg, California
67                 Fort Lauderdale, Florida
68                      Fort Wayne, Indiana
69                     Glendale, California
70                        Hamilton, Montana
71                   Harrisonburg, Virginia
72                        Henderson, Nevada
73                Highland Park, New Jersey
74             Hillsborough, North Carolina
75              Hilo, Big Island of Hawai'i
76              Hilo, Big Island of Hawai’i
77                            Hilo, Hawai'i
78                             Hilo, Hawaii
79                            Hilo, Hawai’i
80            Hilo, Hawai’i Island, Hawai’i
81                         Holualoa, Hawaii
82                        Holualoa, Hawai’i
83                        Holulaloa, Hawaii
84                         Hong Kong, China
85                           Houston, Texas
86                     Hsinchu City, Taiwan
87                          Hsinchu, Taiwan
88                         Hudson, New York
89                       I-Lan City, Taiwan
90                         Ithaca, New York
91                     Jackson, MIssissippi
92                     Jackson, Mississippi
93                       Jakarta, Indonesia
94                  Jersey City, New Jersey
95                     Johns Creek, Georgia
96                             Ka'u, Hawaii
97                    Kansas City, Missouri
98                   Kaohsiung City, Taiwan
99                        Kaohsiung, Taiwan
100                  Kaohslung City, Taiwan
101                         Keelung, Taiwan
102                    Kiambu County, Kenya
103                     Kihei, Maui, Hawaii
104                    Kihei, Maui, Hawai’i
105               Kowloon, Hong Kong, China
106                    La Jolla, California
107                   Lake Forest, Illinois
108                          Lake, Michigan
109                 Langhorne, Pennsylvania
110                      Lee, Massachusetts
111                     Lexington, Virginia
112                    Lexington, Virginia.
113                     Lincoln, California
114                     Livingston, Montana
115  Llayla District, Satipo Province, Peru
116      Lloydminster, Saskatchewan, Canada
117                         London, England
118                 London, Ontario, Canada
119              Long Island City, New York
120                       Longwood, Florida
121                 Los Angeles, California
122                    Louisville, Kentucky
123                            Macao, China
124                      Madison, Wisconsin
125                     Madison, Wisconsin.
126                      Manassas, Virginia
127                       Manlius, New York
128                Markham, Ontario, Canada
129                    Martinez, California
130                       McHenry, Illinois
131                          Miami, Florida
132                    Milwaukee, Wisconsin
133                  Minneapolis, MInnesota
134                  Minneapolis, Minnesota
135                    Minnesota, Minnesota
136               Minxiong, Chia-Yi, Taiwan
137                      Montrose, Colorado
138                Mount Shasta, California
139                  Mountain View, Hawai'i
140                   Mountain View, Hawaii
141                  Mountain View, Hawai’i
142                          Nantou, Taiwan
143               New Brunswick, New Jersey
144                  New Orleans, Louisiana
145                 New Taipei City, Taiwan
146               Newport Beach, California
147              Newtown, Sydney, Australia
148                       Norfolk, Virginia
149             North Hollywood, California
150                     Oakland, California
151               Oakville, Ontario, Canada
152                     Olympia, Washington
153                            Osaka, Japan
154                         Ovledo, Florida
155                         Pahala, Hawai'i
156                          Pahala, Hawaii
157         Pahala, “Big Island” of Hawai’i
158    Paju City (Gyeonggi-do), South Korea
159                        Peoria, Illinois
160              Philadelphia, Pennsylvania
161                        Phoenix, Arizona
162                        Pingtung, Taiwan
163                 Plymouth, Massachusetts
164                         Portland, Maine
165                        Portland, Oregon
166                       Post Falls, Idaho
167            Pu'Er Yunnan Province, China
168           Pu’Er, Yunnan Province, China
169                 Raleigh, North Carolina
170                       Ramsey, Minnesota
171                     Redding, California
172                    Redlands, California
173                            Reno, Nevada
174                      Renton, Washington
175          Richmond Hill, Ontario, Canada
176      Richmond, British Columbia, Canada
177                      Richmond, Virginia
178   Roanoke, Virginia and Floyd, Virginia
179                     Rochester, New York
180                   Sacamento, California
181                                    Sacr
182                   Sacramento, Calfornia
183                  Sacramento, California
184                 Sacramento, Californiaa
185                    Salem, Massachusetts
186                   San Diego, California
187                   San Dimas, California
188               San Francisco, California
189                    San Jose, California
190         San Juan Lachao, Oaxaca, Mexico
191             San Luis Obispo, California
192                  San Rafael, California
193   Santa Ana growing region, El Salvador
194                    Santa Fe, New Mexico
195                Santa Monica, California
196               Santa Rosa Beach, Florida
197                   Satipo Province, Peru
198                       Savannah, Georgia
199                     Seattle, Washington
200                            Seoul, Korea
201                      Seoul, South Korea
202                         Shanghai, China
203                  Silver Lake, Minnesota
204               Sioux Falls, South Dakota
205                             South Korea
206                     Spokane, Washington
207                     St. Louis, MIssouri
208                     St. Louis, Missouri
209                        Suwanee, Georgia
210                           Suzhou, China
211                   Taichung City, Taiwan
212                        Taichung, Taiwan
213                     Tainan City, Taiwan
214                          Tainan, Taiwan
215                     Taipei City, Taiwan
216                          Taipei, Taiwan
217                         Taitung, Taiwan
218                                  Taiwan
219                         Taiyuan, Taiwan
220                    Taoyuan City, Taiwan
221                   Taoyuan City, Taiwan.
222                         Taoyuan, Taiwan
223                       Tequesta, Florida
224                    Thermopolis, Wyoming
225                      Thornton, Colorado
226                        Tiachung, Taiwan
227                          Topeka, Kansas
228                         Toronto, Canada
229                Toronto, Ontario, Canada
230                 Torrington, Connecticut
231                     Truckee, California
232                         Tucson, Arizona
233                         Tulsa, Oklahoma
234                      Upland, California
235     Vancouver, British Columbia, Canada
236                     Ventura, California
237                      Viroqua, Wisconsin
238                        Washington, D.C.
239                          Washington, DC
240               Waterbury Center, Vermont
241                      Waterbury, Vermont
242                           YiLan, Taiwan
243                           Yilan, Taiwan
244                  Yongin-Si, South Korea
245              Yorktown Heights, New York
246                        Youngstown, Ohio
247                          Yunlin, Taiwan
248                     Zhubei City, Taiwan
249                          Zhubei, Taiwan

In [6]:
# Create the inital splits
split_cols = df_coffee_wrangle['roaster_location'].str.split(',', expand=True)

# Assign based on how many parts exist
df_coffee_wrangle['roaster_city'] = split_cols[0].str.strip()
df_coffee_wrangle['roaster_region'] = split_cols[1].str.strip() if split_cols.shape[1] > 1 else None
df_coffee_wrangle['roaster_country'] = split_cols[2].str.strip() if split_cols.shape[1] > 2 else None

In [7]:
df_coffee_wrangle[['roaster_location', 'roaster_city', 'roaster_region', 'roaster_country']].head(20)

             roaster_location roaster_city  roaster_region roaster_country
0        Cleveland, Tennessee    Cleveland       Tennessee            None
1        Cleveland, Tennessee    Cleveland       Tennessee            None
2     Jersey City, New Jersey  Jersey City      New Jersey            None
3             Chia-Yi, Taiwan      Chia-Yi          Taiwan            None
4             Chia-Yi, Taiwan      Chia-Yi          Taiwan            None
5            Taichung, Taiwan     Taichung          Taiwan            None
6              Yunlin, Taiwan       Yunlin          Taiwan            None
7             Chia-Yi, Taiwan      Chia-Yi          Taiwan            None
8             Chia-Yi, Taiwan      Chia-Yi          Taiwan            None
9              Yunlin, Taiwan       Yunlin          Taiwan            None
10             Taipei, Taiwan       Taipei          Taiwan            None
11         Madison, Wisconsin      Madison       Wisconsin            None
12         Madison, Wisconsin      Madison       Wisconsin            None
13         Madison, Wisconsin      Madison       Wisconsin            None
14              Yilan, Taiwan        Yilan          Taiwan            None
15              Yilan, Taiwan        Yilan          Taiwan            None
16         Madison, Wisconsin      Madison       Wisconsin            None
17  Charlotte, North Carolina    Charlotte  North Carolina            None
18         Madison, Wisconsin      Madison       Wisconsin            None
19           Peoria, Illinois       Peoria        Illinois            None

In [8]:
# Countries list
known_countries = sorted([
    'Australia', 'Brazil', 'Burundi', 'Canada', 'China', 'Colombia', 'Costa Rica',
    'El Salvador', 'England', 'Ethiopia', 'Guatemala', 'Guinea', 'Honduras',
    'Hong Kong', 'India', 'Indonesia', 'Japan', 'Kenya', 'Macao', 'Mexico',
    'Nicaragua', 'Panama', 'Peru', 'Puerto Rico', 'South Korea', 'Taiwan',
    'Tanzania', 'Timor', 'United Kingdom', 'United States', 'Yemen'
])

In [9]:
# If a value in roaster_region is actually a country, move it to roaster_country
df_coffee_wrangle['roaster_country'] = df_coffee_wrangle.apply(
    lambda row: row['roaster_region'] if row['roaster_region'] in known_countries else row['roaster_country'],
    axis=1
)

In [10]:
# Work check
# Preview promoted country values without modifying the original column
df_coffee_wrangle['roaster_country_preview'] = df_coffee_wrangle.apply(
    lambda row: row['roaster_region'] if row['roaster_region'] in known_countries else row['roaster_country'],
    axis=1
)

# Display side-by-side comparison
df_coffee_wrangle[['roaster_location', 'roaster_region', 'roaster_country', 'roaster_country_preview']].head(20)

,roaster_location,roaster_region,roaster_country,roaster_country_preview
0,"Cleveland, Tennessee",Tennessee,None,None
1,"Cleveland, Tennessee",Tennessee,None,None
2,"Jersey City, New Jersey",New Jersey,None,None
3,"Chia-Yi, Taiwan",Taiwan,Taiwan,Taiwan
4,"Chia-Yi, Taiwan",Taiwan,Taiwan,Taiwan
5,"Taichung, Taiwan",Taiwan,Taiwan,Taiwan
6,"Yunlin, Taiwan",Taiwan,Taiwan,Taiwan
7,"Chia-Yi, Taiwan",Taiwan,Taiwan,Taiwan
8,"Chia-Yi, Taiwan",Taiwan,Taiwan,Taiwan
9,"Yunlin, Taiwan",Taiwan,Taiwan,Taiwan
10,"Taipei, Taiwan",Taiwan,Taiwan,Taiwan
11,"Madison, Wisconsin",Wisconsin,None,None
12,"Madison, Wisconsin",Wisconsin,None,None
13,"Madison, Wisconsin",Wisconsin,None,None
14,"Yilan, Taiwan",Taiwan,Taiwan,Taiwan
15,"Yilan, Taiwan",Taiwan,Taiwan,Taiwan
16,"Madison, Wisconsin",Wisconsin,None,None
17,"Charlotte, North Carolina",North Carolina,None,None
18,"Madison, Wisconsin",Wisconsin,None,None
19,"Peoria, Illinois",Illinois,None,None

In [11]:
# If country was moved over, remove duplicate from the roaster_region column
df_coffee_wrangle['roaster_region'] = df_coffee_wrangle.apply(
    lambda row: None if row['roaster_region'] in known_countries else row['roaster_region'],
    axis=1
)

In [12]:
# Work check
df_coffee_wrangle[['roaster_location', 'roaster_region', 'roaster_country']].head(20)

             roaster_location  roaster_region roaster_country
0        Cleveland, Tennessee       Tennessee            None
1        Cleveland, Tennessee       Tennessee            None
2     Jersey City, New Jersey      New Jersey            None
3             Chia-Yi, Taiwan            None          Taiwan
4             Chia-Yi, Taiwan            None          Taiwan
5            Taichung, Taiwan            None          Taiwan
6              Yunlin, Taiwan            None          Taiwan
7             Chia-Yi, Taiwan            None          Taiwan
8             Chia-Yi, Taiwan            None          Taiwan
9              Yunlin, Taiwan            None          Taiwan
10             Taipei, Taiwan            None          Taiwan
11         Madison, Wisconsin       Wisconsin            None
12         Madison, Wisconsin       Wisconsin            None
13         Madison, Wisconsin       Wisconsin            None
14              Yilan, Taiwan            None          Taiwan
15              Yilan, Taiwan            None          Taiwan
16         Madison, Wisconsin       Wisconsin            None
17  Charlotte, North Carolina  North Carolina            None
18         Madison, Wisconsin       Wisconsin            None
19           Peoria, Illinois        Illinois            None

Looks like it worked moving over the countries to the roaster_country column and removing the duplicates in the roaster region. Later the None will become unknown.

In [13]:
# Address the us states 
us_states = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
    'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
    'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
    'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
    'Wisconsin', 'Wyoming'
]

In [14]:
#  Fill in roaster_country Where Region Is a U.S. State
df_coffee_wrangle['roaster_country'] = df_coffee_wrangle.apply(
    lambda row: 'United States' if row['roaster_region'] in us_states and pd.isna(row['roaster_country']) else row['roaster_country'],
    axis=1
)

In [15]:
# Work check
df_coffee_wrangle[['roaster_location', 'roaster_region', 'roaster_country']].head(20)

             roaster_location  roaster_region roaster_country
0        Cleveland, Tennessee       Tennessee   United States
1        Cleveland, Tennessee       Tennessee   United States
2     Jersey City, New Jersey      New Jersey   United States
3             Chia-Yi, Taiwan            None          Taiwan
4             Chia-Yi, Taiwan            None          Taiwan
5            Taichung, Taiwan            None          Taiwan
6              Yunlin, Taiwan            None          Taiwan
7             Chia-Yi, Taiwan            None          Taiwan
8             Chia-Yi, Taiwan            None          Taiwan
9              Yunlin, Taiwan            None          Taiwan
10             Taipei, Taiwan            None          Taiwan
11         Madison, Wisconsin       Wisconsin   United States
12         Madison, Wisconsin       Wisconsin   United States
13         Madison, Wisconsin       Wisconsin   United States
14              Yilan, Taiwan            None          Taiwan
15              Yilan, Taiwan            None          Taiwan
16         Madison, Wisconsin       Wisconsin   United States
17  Charlotte, North Carolina  North Carolina   United States
18         Madison, Wisconsin       Wisconsin   United States
19           Peoria, Illinois        Illinois   United States

In [ ]:
# Drop these columns used for splitting and previewing
df_coffee_wrangle.drop(columns=[
    'origin_part_1',
    'origin_part_2',
    'origin_part_3',
    'roaster_country_preview'
], inplace=True)

In [16]:
df_coffee_wrangle.head()

,coffee_name,total_score,roaster_location,coffee_origin,roast_level,agtron_roast,price_usd,quantity_g,usd_per_gram,roaster_city,roaster_region,roaster_country,roaster_country_preview
0,Colombia Finca Campo Hermosa,94.0,"Cleveland, Tennessee","Quindio Department, Colombia",Light,82.0,29.99,226.8,$29.99 / 226.8g,Cleveland,Tennessee,United States,None
1,Colombia Finca La Sirena Mango Co-Ferment,94.0,"Cleveland, Tennessee","Quindio Department, Colombia",Light,87.0,22.99,226.8,$22.99 / 226.8g,Cleveland,Tennessee,United States,None
2,In Bloom,94.0,"Jersey City, New Jersey",Colombia; Ethiopia,Light,88.0,25.00,250.0,$25.0 / 250.0g,Jersey City,New Jersey,United States,None
3,Ethiopia Washed Kaffa Gimbo Lot Rich Espresso,96.0,"Chia-Yi, Taiwan","Gimbo, Kaffa Province, Ethiopia",Medium Light,77.0,8.17,226.8,$8.17 / 226.8g,Chia-Yi,None,Taiwan,Taiwan
4,Ethiopia Natural Gute Bona,95.0,"Chia-Yi, Taiwan","Sidamo growing region, southern Ethiopia",Medium Light,78.0,13.07,226.8,$13.07 / 226.8g,Chia-Yi,None,Taiwan,Taiwan

## 4. Data Wrangle - Coffee Origin

In [17]:
# Get the list of places
# Expand display limit
pd.set_option('display.max_rows', None)

# Show all unique coffee_origin values
pd.DataFrame({'coffee_origin': sorted(df_coffee_wrangle['coffee_origin'].dropna().unique())})

                                         coffee_origin
0                 Acatenango growing region, Guatemala
1                Acatenango growing region, Guatemala.
2         Acatenango growing region, central Guatemala
3        Acatenango growing region, central Guatemala.
4      Acatenango, Chimaltenango Department, Guatemala
5                 Acatenango, Chimaltenango, Guatemala
6                                Acatenango, Guatemala
7                    Aceh Province, Sumatra, Indonesia
8            Aceh Province, northern Sumatra Indonesia
9          Aceh Province, northern Sumatra, Indonesia.
10                            Aceh, Sumatra, Indonesia
11                 Acevedo, Huila Department, Colombia
12                                              Africa
13                                Africa; Asia Pacific
14   Agaro District, Jimma Zone, west-central Ethiopia
15   Agaro Duromina, Jimma Zone, Oromia State, Ethi...
16     Agaro Gera, Jimma Zone, Oromia Region, Ethiopia
17      Agaro Gera, Jimma Zone, Oromia State, Ethiopia
18                      Agaro, Oromia region, Ethiopia
19   Al Hayma growing region, Al Kharijiyah Distric...
20          Al Hayma region, Sana’a Governorate, Yemen
21                 Al Hayma, Sana'a Governorate, Yemen
22                  Al Mahjr, Al Hayma District, Yemen
23                        Al Mashtal ul Burhani, Yemen
24            Al Obrah, Hayma Dakhaliya, Sana'a, Yemen
25           Al Wadi region, Sana’a Governorate, Yemen
26                Al-Durrar, Sana’a Governorate, Yemen
27                                    Al-Haimah, Yemen
28                Alajuela, Central Valley, Costa Rica
29                                Alajuela, Costa Rica
30   Aleta Wondo, Sidama (also Sidamo) growing regi...
31               Algeciras, Huila Department, Colombia
32             Alishan Township, Chiayi County, Taiwan
33                             Alishan, Chaiyi, Taiwan
34                       Alishan, Chia-Yi City, Taiwan
35                            Alishan, Chia-Yi, Taiwan
36                                     Alishan, Taiwan
37   Alto Jaramillo, Boquete growing region, wester...
38   Alto Quiel, Boquete growing region, western Pa...
39                        Alto Quiel, Boquete, Panama.
40                                  Alto Quiel, Panama
41   Amaro Mountains, Sidama (also Sidamo) growing ...
42                    Amaro region, southern Ethiopia.
43                              Amaybamba, Cusco, Peru
44                           Antigua Valley, Guatemala
45                   Antigua growing region, Guatemala
46     Antigua growing region, south-central Guatemala
47   Antigua valley, Sacatepequez Department, Guate...
48                   Antigua valley, central Guatemala
49                                  Antigua, Guatemala
50                      Antioquia Department, Colombia
51            Antioquia Department, northwest Colombia
52                                 Antioquia, Colombia
53                   Apaneca Ilamatepec mountain range
54                        Apaneca, Ataco, El Salvador.
55                                Apaneca, El Salvador
56      Apaneca-Ilamatepec Mountain Range, El Salvador
57      Apaneca-Ilamatepec growing region, El Salvador
58                     Apaneca-Ilamatepec, El Salvador
59                 Aponte, Nariño Department, Colombia
60        Aqua Dulce, Cuilco, Huehuetenango, Guatemala
61                                 Aranjuez, Nicaragua
62             Aratoca, Santander Department, Colombia
63   Arbegona, Sidama (also Sidamo) growing region,...
64                   Arbegona, Sidama Region, Ethiopia
65   Arbegona, Sidamo growing region, south-central...
66                  Argopuro Mountain, Java, Indonesia
67               Armenia, Quindio Department, Colombia
68                    Arusha Region, northern Tanzania
69                 Bambito Mountains, Chiriqui, Panama
70                 Bani Ismail District, Sana'a, Yemen
71                    Bani Matar growing region, Yemen
72          Baringo and Nakura Counties, central Kenya
73                  Bench Maji Zone, Southern Ethiopia
74                  Bench Maji Zone, southern Ethiopia
75                  Bench-Maji Zone, Southern Ethiopia
76                  Bench-Maji Zone, southern Ethiopia
77                   Bench-Maji Zone, western Ethiopia
78     Bensa District, Sidamo growing region, Ethiopia
79      Bensa district, Sidama Zone, southern Ethiopia
80   Bensa, Guji Zone, Oromia Region, southern Ethi...
81                                Big Island of Hawaii
82   Bita Genet District, Keffa Zone, southwestern ...
83            Boke, Gamo Gofa Zone, Southern Ethiopia.
84            Bombe Mountains, Sidama Region, Ethiopia
85    Bombe Mountains, Sidama growing region, Ethiopia
86   Bombe Village, Bensa District, Sidamo growing ...
87   Bombe mountains, Sidama Region, southern Ethiopia
88   Bombe mountains, Sidamo Region, southern Ethiopia
89                 Bona Zuria, Sidama Region, Ethiopia
90   Bonga Forest, Keficho-Shekicho Zone, southwest...
91                      Boquete growing region, Panama
92              Boquete growing region, western Panama
93             Boquete growing region, western Panama.
94                                     Boquete, Panama
95   Borena Zone, Yirgacheffe growing region, south...
96                       Brazil and four other origins
97                       Brazil; Ethiopia; El Salvador
98    Brazil; Mandheling, Sumatra; Guatemala; Ethiopia
99                           Brunca Region, Costa Rica
100                  Brunca growing region, Costa Rica
101     Bruselas, Pitalito, Huila Department, Colombia
102      Buhinyuza District, Muhinga Province, Burundi
103                      Bungoma region, western Kenya
104                     Bungoma region, western Kenya.
105                                     Bungoma, Kenya
106  Bursa Village, Arbegona, Sidama growing region...
107                                            Burundi
108             Caicedonia, Cauca Department, Colombia
109    Caicedonia, Valle de Cauca Department, Colombia
110   Caicedonia, Valle del Cauca Department, Colombia
111  Caicendonia, Valle Del Cauca, Cauca Department...
112             Caicendonia, Valle Del Cauca, Colombia
113                                    Cajamarca, Peru
114                    Caldas growing region, Colombia
115                                   Caldas, Colombia
116                Caldono, Calda Department, Colombia
117  Calzontes Arriba, Santa Ana Department, El Sal...
118  Cantón El Tunel, La Palma, Chalatenango, El Sa...
119                  Caranavi growing region, Bolivia.
120  Carmo de Minas growing region, Minas Gerais St...
121  Carmo de Minas growing region, Minas Gerais St...
122                         Cauca Department, Colombia
123               Cauca Department, southern Colombia.
124                                    Cauca, Colombia
125       Cañas Verdes, Boquete growing region, Panama
126  Cañas Verdes, Boquete growing region, western ...
127  Cañas Verdes, Boquete growing region, western ...
128                      Cañas Verdes, Boquete, Panama
129  Celinga Village, Yirgacheffe growing region, s...
130                                   Central America.
131        Central America; South America; East Africa
132          Central America; South America; Indonesia
133                                      Central Kenya
134                                     Central Kenya.
135  Central Kenya; Toraja growing region, southwes...
136                            Central Province, Kenya
137                         Central Valley, Costa Rica
138                        Central Valley, Costa Rica.
139                                      Central Yemen
140              Cerrado Mineiro, Minas Gerais, Brazil
141             Chachagüí, Nariño Department, Colombia
142               Chalatenango Department, El Salvador
143  Chalatenango growing region, northwestern El S...
144                          Chalatenango, El Salvador
145  Chelba Station , Yirgacheffe, Gedeo Zone, SNNP...
146  Chelbessa, Gedeb, Yirgacheffe, south-central E...
147    Chelchele, Gedeb District, Gedeo Zone, Ethiopia
148          Chericho, Sidamo growing region, Ethiopia
149                              Chiapas State, Mexico
150               Chimaltenango Department, Guatemala.
151             Chinchina, Caldas Department, Colombia
152                          Chiriqui Province, Panama
153              Chiriqui Province, far western Panama
154                  Chiriqui Province, western Panama
155                    Chiriqui growing region, Panama
156   Chiriqui, Boquete growing region, western Panama
157                          Chiriqui, western Panama.
158                                   Chiriquí, Panama
159        Chirripo, Brunca growing region, Costa Rica
160  Circasia Municipality, Quindio Department, Col...
161             Circasia, Quindio Department, Colombia
162                        Circasia, Quindio, Colombia
163     Ciudad Bolivar, Antioquia Department, Colombia
164                Ciudad Bolivar, Antioquia, Colombia
165                   Coatepec, Veracruz State, Mexico
166  Cobán growing region, Alta Verapaz Department,...
167      Cobán growing region, Alta Verapaz, Guatemala
168            Cobán growing region, central Guatemala
169   Cobán region, Alta Verapaz Department, Guatemala
170                                           Colombia
171                          Colombia, Ethiopia, Kenya
172              Colombia; Costa Rica; Kenya; Ethiopia
173                                 Colombia; Ethiopia
174                                Colombia; Guatemala
175          Colombia; Guatemala; Costa Rica; Ethiopia
176                      Colombia; Guatemala; Ethiopia
177                        Colombia; Guatemala; Mexico
178                   Colombia; Peru; Rwanda; Ethiopia
179                  Conganama, Loja Province, Ecuador
180                                    Congo; Ethiopia
181                           Congonama, Loja, Ecuador
182               Coorg growing region, southern India
183                         Copey District, Costa Rica
184              Cordillera de Llamatepec, El Salvador
185                                         Costa Rica
186                               Costa Rica; Ethiopia
187                                 Costa Rica; Mexico
188                  Cundinamarca Department, Colombia
189          Cundinamarca Department, central Colombia
190                             Cundinamarca, Colombia
191                                 Cusco Region, Peru
192                                        Cusco, Peru
193  Cyinzuzi Sector, Rulindo District, Northern Pr...
194  Dame Debaye washing station, Guji growing regi...
195                                 Dipilto, Nicaragua
196      Djimma Limu, Oromia Region, southern Ethiopia
197      Djimma growing region, Oromia State, Ethiopia
198  Dolok Sanggul, Lintong growing region, North S...
199           Dota, Tarrazú growing region, Costa Rica
200                          Dota, Tarrazú, Costa Rica
201                   East Africa and Java, Indonesia.
202  Eastern Java, Indonesia; Sidamo growing region...
203                                           Ecuador.
204  El Aguacatal, Hoja Blanca, Cuilco, Huehuetenan...
205  El Boqueron, Volcan de San Salvador, El Salvador.
206  El Bálsamo Quetzaltepec growing region, El Sal...
207               El Bálsamo Quetzaltepec, El Salvador
208  El Bálsamo, Quetzaltepec growing region, El Sa...
209      El Carmen Cautivo, Tabaconas, Cajamarca, Peru
210  El Chaco Canton, Parroquia Santa Rosa, Napo Pr...
211            El Guarco, Cartago Province, Costa Rica
212    El Jardin, Pitalito, Huila Department, Colombia
213      El Quiche Department, south central Guatemala
214          El Salto, Boquete growing region, Panama.
215                                        El Salvador
216                                El Salvador; Kenya.
217                      Elida Estate, western Panama.
218                Embu County, Eastern Province Kenya
219               Embu County, Eastern Province, Kenya
220                                 Embu County, Kenya
221           Embu District, Central Highlands, Kenya.
222                                        Embu, Kenya
223                                           Ethiopia
224                                   Ethiopia, Brazil
225                                Ethiopia, Guatemala
226                           Ethiopia; Burundi; Kenya
227                                 Ethiopia; Colombia
228                 Ethiopia; Colombia; Panama; Mexico
229                               Ethiopia; Costa Rica
230         Ethiopia; Democratic Republic of the Congo
231                       Ethiopia; Dominican Republic
232                                Ethiopia; Guatemala
233  Ethiopia; Guatemala; El Salvador; Panama; Cost...
234                      Ethiopia; Guatemala; Honduras
235                         Ethiopia; Guatemala; Kenya
236     Ethiopia; Guatemala; Papua New Guinea; Sumatra
237               Ethiopia; Honduras; Kenya; Guatemala
238                                    Ethiopia; Kenya
239                                   Ethiopia; Kenya.
240                   Ethiopia; Kenya; Bolivia; Panama
241                             Ethiopia; Kenya; China
242              Ethiopia; Kenya; Colombia; Costa Rica
243      Ethiopia; Kenya; Colombia; Nicaragua; Sumatra
244              Ethiopia; Papua New Guinea; Guatemala
245                         Ethiopia; Rwanda; Colombia
246                Ethiopia; Sumatra; Central America.
247                 Finca Santa Teresa, Volcan, Panama
248  Fondo Paez Cooperative, Valle de Cauca Departm...
249      Gaitania, Tolima Department, central Colombia
250                           Gakenke District, Rwanda
251                          Gakenke District, Rwanda.
252  Gayo (also Aceh) growing region, Aceh Province...
253               Gedeb District, Gedeo Zone, Ethiopia
254               Gedeb District, Gedeo Zone, southern
255      Gedeb District, Gedeo Zone, southern Ethiopia
256  Gedeb District, Yirgacheffe growing region, so...
257  Gedeb District, Yirgacheffe growing region, so...
258                      Gedeo Zone, Kochere, Ethiopia
259         Gedeo Zone, SNNP Region, southern Ethiopia
260               Gedeo Zone, SNNPR, southern Ethiopia
261  Gedeo Zone, Yirgacheffe growing region, southe...
262  Gedeo Zone, Yirgacheffe growing region, southe...
263                      Gedeo Zone, southern Ethiopia
264                     Gedeo Zone, southern Ethiopia.
265  Gedeo zone, Yirgacheffe growing region, south-...
266  Gedeo, Yirgacheffe growing region, south-centr...
267  Gera District of Oromia Region, western Ethiopia.
268  Gerbicho Rogicha, Bule Hora District, Guji Zon...
269  Gichugu Division, Kirinyaga County, central Kenya
270                    Gimbo, Kaffa Province, Ethiopia
271                       Giraldo, Antioquia, Colombia
272  Gori Gesha Forest, Bench Maji Zone, SNNPR Regi...
273             Guama Village, Kirinyaga County, Kenya
274            Guatemala and other undisclosed origins
275                        Guatemala; Brazil; Colombia
276                           Guatemala; Brazil; Kenya
277                      Guatemala; Colombia; Ethiopia
278                                Guatemala; Ethiopia
279                               Guatemala; Ethiopia.
280             Guatemala; Ethiopia; Brazil; Indonesia
281                      Guatemala; Ethiopia; Colombia
282                      Guatemala; Honduras; Colombia
283                      Guatemala; Honduras; Ethiopia
284                             Guerrero State, Mexico
285   Guji Zone, Borena Hagermariam District, Ethiopia
286                 Guji Zone, Oromia Region, Ethiopia
287  Guji Zone, Oromia Region, Hambela Woreda, Ethi...
288  Guji Zone, Oromia Region, Sidama Province, Eth...
289  Guji Zone, Oromia Region, Sidamo growing regio...
290  Guji Zone, Oromia Region, Sidamo growing regio...
291        Guji Zone, Oromia Region, Southern Ethiopia
292   Guji Zone, Oromia Region, south-central Ethiopia
293        Guji Zone, Oromia Region, southern Ethiopia
294                 Guji Zone, Oromia region, Ethiopia
295        Guji Zone, Oromia region, southern Ethiopia
296      Guji Zone, Sidama Province, southern Ethiopia
297     Guji Zone, Sidama Province, southern Ethiopia.
298                       Guji Zone, southern Ethiopia
299        Guji growing region, south-central Ethiopia
300          Gunung Tujuh, Kerinci, Sumatra, Indonesia
301                      Hambela Dimtu, Guji, Ethiopia
302       Hambela Wamena District, Guji Zone, Ethiopia
303  Hambela Wamena District, Guji Zone, Oromia Reg...
304  Hambela Wamena District, Guji Zone, Oromia reg...
305        Hambela Wamena, Guji Zone, Oromia, Ethiopia
306  Hambela district, Oromia growing region, south...
307                       Haraaz growing region, Yemen
308                                      Haraaz, Yemen
309  Haraz (also spelled Haraaz) growing region, no...
310  Haro Wachu, Uraga, Guji Zone, Oromia Region, E...
311  Harrar region of eastern Ethiopia; east Java, ...
312  Hayisa Village, Bure Woreda, Sidama Zone, Ethi...
313  Hayma Dakhiliya growing region, Sana’a Governo...
314              Hayma Kharijiya growing region, Yemen
315                         Hayma, north-central Yemen
316  Herrera, Tolima Department, west-central Colom...
317              Hoja Blanca, Huehuetenango, Guatemala
318                                   Holualoa, Hawaii
319                   Holualoa, Hawai’i Island, Hawaii
320  Holualoa, Kona growing region, Big Island of H...
321              Holualoa, Kona, Big Island of Hawai’i
322  Holualoa, North Kona District, “Big Island” of...
323     Holualoa, North Kona growing district, Hawaii.
324  Holualoa, North Kona growing district, “Big Is...
325  Holualoa, North Kona growing district, “Big Is...
326  Holualoa, North Kona growing district, “Big Is...
327  Holualoa, North Kona growing district, “Big Is...
328                      Honduras; Guatemala; Colombia
329                          Honduras; Kenya; Ethiopia
330        Horcheta, Chiriqui Province, western Panama
331                Horqueta, Chiriquí, Boquete, Panama
332  Huarango, San Ignacio, Cajamarca growing regio...
333                Huehuetenango Department, Guatemala
334            Huehuetenango growing region, Guatemala
335           Huehuetenango growing region, Guatemala.
336  Huehuetenango growing region, Guatemala; Sidam...
337  Huehuetenango growing region, north-central Gu...
338  Huehuetenango growing region, northwestern Gua...
339                           Huehuetenango, Guatemala
340                         Huila Department, Colombia
341                Huila Department, southern Colombia
342               Huila Department, southern Colombia.
343                    Huila growing region, Colombia.
344                                    Huila, Colombia
345  Hōlualoa, North Kona growing region, Hawai’i I...
346               Hōlualoa, North Kona, Hawai’i Island
347                 Ibarra, Imbabura Province, Ecuador
348            Illubabor Zone, Oromia Region, Ethiopia
349                         Imbabura Province, Ecuador
350             Incawasi, La Convencion Province, Peru
351      Indonesia, India, Guatemala, Brazil, Ethiopia
352                                Indonesia; Ethiopia
353                   Inza, Cauca Department, Colombia
354                                    Ipanema, Brazil
355             Jabal Haraz, Sana’a Governorate, Yemen
356                 Jambi Province, Sumatra, Indonesia
357                                  Jaramillo, Panama
358                              Jaén, Cajamarca, Peru
359       Jimma Zone, Oromia Region, southern Ethiopia
360                 Jimma Zone, Oromia State, Ethiopia
361       Jimma Zone, Oromia region, southern Ethiopia

In [18]:
# Define known countries
known_countries = sorted([
    'australia', 'brazil', 'burundi', 'canada', 'china', 'colombia', 'costa rica',
    'el salvador', 'england', 'ethiopia', 'guatemala', 'guinea', 'honduras',
    'hong kong', 'india', 'indonesia', 'japan', 'kenya', 'macao', 'mexico',
    'nicaragua', 'panama', 'peru', 'puerto rico', 'rwanda', 'south korea',
    'taiwan', 'tanzania', 'timor', 'united kingdom', 'united states', 'yemen'
])

In [19]:
# Split the coffee_origin string into parts using commas or semicolons
origin_split = df_coffee_wrangle['coffee_origin'].str.lower().str.strip().str.split(r'[;,]', expand=True)

In [20]:
# Assign each split part to a new column
df_coffee_wrangle.loc[:, 'origin_part_1'] = origin_split[0].str.strip()
df_coffee_wrangle.loc[:, 'origin_part_2'] = origin_split[1].str.strip() if origin_split.shape[1] > 1 else None
df_coffee_wrangle.loc[:, 'origin_part_3'] = origin_split[2].str.strip() if origin_split.shape[1] > 2 else None
df_coffee_wrangle.loc[:, 'origin_part_4'] = origin_split[3].str.strip() if origin_split.shape[1] > 3 else None

In [21]:
# Move over a known country from part_2 or part_3 if present
# Move over a known country from any origin part
# Initialize coffee_country before applying logic
df_coffee_wrangle['coffee_country'] = 'unknown'

# Infer country from origin parts
df_coffee_wrangle['coffee_country'] = df_coffee_wrangle.apply(
    lambda row: next((part for part in [
        row['origin_part_1'], row['origin_part_2'], row['origin_part_3'], row['origin_part_4']
    ] if part in known_countries), row['coffee_country']),
    axis=1
)

In [22]:
# If no country was moved over, scan all parts for known countries
df_coffee_wrangle.loc[:, 'coffee_country'] = df_coffee_wrangle.apply(
    lambda row: next((part for part in [
        row['origin_part_1'], row['origin_part_2'], row['origin_part_3'], row['origin_part_4']
    ] if part in known_countries), row['coffee_country']),
    axis=1
)

In [23]:
# Relabel headers
df_coffee_wrangle.loc[:, 'coffee_city'] = df_coffee_wrangle['origin_part_1']
df_coffee_wrangle.loc[:, 'coffee_region'] = df_coffee_wrangle['origin_part_2']

In [24]:
# Drop columns that aren't needed
columns_to_drop = ['origin_part_1', 'origin_part_2', 'origin_part_3', 'origin_part_4']
existing_cols = [col for col in columns_to_drop if col in df_coffee_wrangle.columns]
df_coffee_wrangle = df_coffee_wrangle.drop(columns=existing_cols)

In [25]:
# Add multi-orgin flag to prevent data removal
df_coffee_wrangle['multi_origin_flag'] = df_coffee_wrangle['coffee_origin'].str.contains(';', case=False, na=False)

In [26]:
# Clean coffee_city
df_coffee_wrangle.loc[
    (~df_coffee_wrangle['multi_origin_flag']) & df_coffee_wrangle['coffee_city'].isin(known_countries),
    'coffee_city'
] = None

In [27]:
# Clean coffee_region
df_coffee_wrangle.loc[
    (~df_coffee_wrangle['multi_origin_flag']) & df_coffee_wrangle['coffee_region'].isin(known_countries),
    'coffee_region'
] = None

In [28]:
# Missing values as unknown
location_cols = [
    'coffee_city', 'coffee_region', 'coffee_country',
    'roaster_city', 'roaster_region', 'roaster_country'
]

df_coffee_wrangle.loc[
    df_coffee_wrangle[location_cols].isna().all(axis=1),
    location_cols
] = 'unknown'

In [29]:
# Ensuring the new columns have a data type
df_coffee_wrangle = df_coffee_wrangle.astype({
    'coffee_city': 'string',
    'coffee_region': 'string',
    'coffee_country': 'string',
    'roaster_city': 'string',
    'roaster_region': 'string',
    'roaster_country': 'string'
})

In [30]:
#Cast location columns to string before filling
location_cols = [
    'coffee_city', 'coffee_region', 'coffee_country',
    'roaster_city', 'roaster_region', 'roaster_country'
]

# Cast to string to avoid dtype conflict
df_coffee_wrangle[location_cols] = df_coffee_wrangle[location_cols].astype('string')

# Now safely fill missing values
df_coffee_wrangle[location_cols] = df_coffee_wrangle[location_cols].fillna('unknown')

In [31]:
# Replace actual missing values (None/NaN) with 'unknown'
df_coffee_wrangle.fillna('unknown', inplace=True)

C:\Users\Chase\AppData\Local\Temp\ipykernel_16676\3533287444.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_coffee_wrangle.fillna('unknown', inplace=True)

In [32]:
# Rearrange the columns for better flow
# Define final column order
final_columns = [
    'coffee_name',
    'total_score',
    'roast_level',
    'agtron_roast',
    'price_usd',
    'quantity_g',
    'usd_per_gram',
    'roaster_location',
    'roaster_city',
    'roaster_region',
    'roaster_country',
    'coffee_origin',
    'coffee_city',
    'coffee_region',
    'coffee_country'
]

# Reorder DataFrame
df_coffee_wrangle = df_coffee_wrangle[final_columns]

In [33]:
# Make text lowercase
# Apply lowercase to all object or string columns
for col in df_coffee_wrangle.columns:
    if df_coffee_wrangle[col].dtype == 'object' or df_coffee_wrangle[col].dtype.name == 'string':
        df_coffee_wrangle[col] = df_coffee_wrangle[col].astype(str).str.lower()

In [34]:
# Clean up data a bit
df_coffee_wrangle[string_cols] = df_coffee_wrangle[string_cols].apply(lambda col: col.str.strip())

NameError: name 'string_cols' is not defined

In [35]:
# Work check
df_coffee_wrangle.head(20)

,coffee_name,total_score,roast_level,agtron_roast,price_usd,quantity_g,usd_per_gram,roaster_location,roaster_city,roaster_region,roaster_country,coffee_origin,coffee_city,coffee_region,coffee_country
0,colombia finca campo hermosa,94.0,light,82.0,29.99,226.8,$29.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,united states,"quindio department, colombia",quindio department,unknown,colombia
1,colombia finca la sirena mango co-ferment,94.0,light,87.0,22.99,226.8,$22.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,united states,"quindio department, colombia",quindio department,unknown,colombia
2,in bloom,94.0,light,88.0,25.0,250.0,$25.0 / 250.0g,"jersey city, new jersey",jersey city,new jersey,united states,colombia; ethiopia,colombia,ethiopia,colombia
3,ethiopia washed kaffa gimbo lot rich espresso,96.0,medium light,77.0,8.17,226.8,$8.17 / 226.8g,"chia-yi, taiwan",chia-yi,unknown,taiwan,"gimbo, kaffa province, ethiopia",gimbo,kaffa province,ethiopia
4,ethiopia natural gute bona,95.0,medium light,78.0,13.07,226.8,$13.07 / 226.8g,"chia-yi, taiwan",chia-yi,unknown,taiwan,"sidamo growing region, southern ethiopia",sidamo growing region,southern ethiopia,unknown
5,white geisha blend espresso,95.0,medium light,78.0,39.0,226.8,$39.0 / 226.8g,"taichung, taiwan",taichung,unknown,taiwan,panama; ethiopia,panama,ethiopia,panama
6,yunlin natural geisha cpag-1,95.0,medium light,78.0,26.14,113.4,$26.14 / 113.4g,"yunlin, taiwan",yunlin,unknown,taiwan,"yunlin, taiwan",yunlin,unknown,taiwan
7,colombia natural huila eulises guzman,94.0,medium light,80.0,11.44,226.8,$11.44 / 226.8g,"chia-yi, taiwan",chia-yi,unknown,taiwan,"huila department, colombia",huila department,unknown,colombia
8,peru washed cusco buena vista soola sl09,94.0,medium light,77.0,9.8,113.4,$9.8 / 113.4g,"chia-yi, taiwan",chia-yi,unknown,taiwan,"cusco, peru",cusco,unknown,peru
9,yunlin natural geisha,94.0,light,84.0,19.61,113.4,$19.61 / 113.4g,"yunlin, taiwan",yunlin,unknown,taiwan,"yunlin, taiwan",yunlin,unknown,taiwan
10,hechi,94.0,light,86.0,10.78,226.8,$10.78 / 226.8g,"taipei, taiwan",taipei,unknown,taiwan,"sidamo growing region, southern ethiopia",sidamo growing region,southern ethiopia,unknown
11,las margaritas sudan rume,95.0,light,84.0,27.0,226.8,$27.0 / 226.8g,"madison, wisconsin",madison,wisconsin,united states,"caicendonia, valle del cauca, cauca department...",caicendonia,valle del cauca,colombia
12,wilton benitez geisha,95.0,light,84.0,26.0,226.8,$26.0 / 226.8g,"madison, wisconsin",madison,wisconsin,united states,"piendamo, cauca department, colombia",piendamo,cauca department,colombia
13,itumpi tanzania,94.0,medium light,81.0,22.0,340.19,$22.0 / 340.19g,"madison, wisconsin",madison,wisconsin,united states,"mbozi district, songwe region, tanzania",mbozi district,songwe region,tanzania
14,ethiopia yirgacheffe g1 gotiti angel station g...,94.0,light,82.0,17.97,200.0,$17.97 / 200.0g,"yilan, taiwan",yilan,unknown,taiwan,"gedeb district, gedeo zone, southern ethiopia",gedeb district,gedeo zone,unknown
15,ethiopia guji hambela buku abel bastet geisha ...,94.0,light,85.0,17.97,200.0,$17.97 / 200.0g,"yilan, taiwan",yilan,unknown,taiwan,"guji zone, oromia region, southern ethiopia",guji zone,oromia region,unknown
16,finca cruz loma ecuador geisha,96.0,medium light,77.0,32.0,226.8,$32.0 / 226.8g,"madison, wisconsin",madison,wisconsin,united states,"san josé de minas, pichincha province, ecuador",san josé de minas,pichincha province,unknown
17,costa rica finca el cañal,95.0,light,88.0,30.0,340.19,$30.0 / 340.19g,"charlotte, north carolina",charlotte,north carolina,united states,"alajuela, central valley, costa rica",alajuela,central valley,costa rica
18,hambela dabaye ethiopia,95.0,light,87.0,24.0,226.8,$24.0 / 226.8g,"madison, wisconsin",madison,wisconsin,united states,"guji growing region, south-central ethiopia",guji growing region,south-central ethiopia,unknown
19,brazil vinhal grape starfruit,94.0,medium light,77.0,21.0,340.19,$21.0 / 340.19g,"peoria, illinois",peoria,illinois,united states,"cerrado mineiro, minas gerais, brazil",cerrado mineiro,minas gerais,brazil

## 5. Wrangle Region

In [36]:
# Strip all unicode, leave only letters
def strip_unicode(text):
    if pd.isna(text):
        return 'unknown'
    # Remove non-ASCII characters
    ascii_text = text.encode('ascii', 'ignore').decode('ascii')
    # Remove all punctuation, digits, and symbols — keep only letters and spaces
    clean_text = re.sub(r'[^a-zA-Z\s]', '', ascii_text)
    return clean_text.lower().strip()

## 6. Wrangle Coffee Region

##### Hawaii Normalization

In [37]:
# Strip unicode from coffee_region
df_coffee_wrangle['coffee_region'] = df_coffee_wrangle['coffee_region'].apply(strip_unicode)

In [38]:
# Preview work
df_coffee_wrangle['coffee_region'].value_counts(dropna=False).head(30)

coffee_region
unknown                        486
southern ethiopia              237
southcentral kenya             159
western panama                 123
oromia region                  113
southcentral ethiopia           72
big island of hawaii            51
north kona growing district     47
cauca department                42
yirgacheffe growing region      29
gedeo zone                      28
ethiopia                        27
central kenya                   26
guji zone                       26
huila department                24
guatemala                       22
north sumatra province          22
sumatra                         19
colombia                        18
volcan                          14
northern sumatra                14
jimma zone                      14
kenya                           13
boquete growing region          13
central highlands               12
southern colombia               12
chiriqui province               12
kona                            11
quindio department              10
valle del cauca                 10
Name: count, dtype: int64

In [42]:
# Work check
df_coffee_wrangle[['coffee_origin', 'coffee_region']].head(50)

,coffee_origin,coffee_region
0,"quindio department, colombia",unknown
1,"quindio department, colombia",unknown
2,colombia; ethiopia,ethiopia
3,"gimbo, kaffa province, ethiopia",kaffa province
4,"sidamo growing region, southern ethiopia",southern ethiopia
5,panama; ethiopia,ethiopia
6,"yunlin, taiwan",unknown
7,"huila department, colombia",unknown
8,"cusco, peru",unknown
9,"yunlin, taiwan",unknown
10,"sidamo growing region, southern ethiopia",southern ethiopia
11,"caicendonia, valle del cauca, cauca department...",valle del cauca
12,"piendamo, cauca department, colombia",cauca department
13,"mbozi district, songwe region, tanzania",songwe region
14,"gedeb district, gedeo zone, southern ethiopia",gedeo zone
15,"guji zone, oromia region, southern ethiopia",oromia region
16,"san josé de minas, pichincha province, ecuador",pichincha province
17,"alajuela, central valley, costa rica",central valley
18,"guji growing region, south-central ethiopia",southcentral ethiopia
19,"cerrado mineiro, minas gerais, brazil",minas gerais
20,"sidamo growing region, southern ethiopia",southern ethiopia
21,"algeciras, huila department, colombia",huila department
22,"santa maria, huila department, colombia",huila department
23,"yirgacheffe growing region, southern ethiopia",southern ethiopia
24,"caicedonia, cauca department, colombia",cauca department
25,"kirinyaga district, south-central kenya",southcentral kenya
26,"kaʻū growing region, hawai’i island, hawai’i",hawaii island
27,"kaʻū growing region, hawai’i island, hawai’i",hawaii island
28,"huila department, colombia",unknown
29,"rustiro, rwanda",unknown
30,"saraguro, loja, ecuador",loja
31,"jaén, cajamarca, peru",cajamarca
32,"sidamo growing region, southern ethiopia",southern ethiopia
33,"bursa village, arbegona, sidama growing region...",arbegona
34,"ka’u growing region, hawai’i island, hawai’i",hawaii island
35,"ka’u growing region, hawai’i island, hawai’i",hawaii island
36,"kona district, hawai’i island, hawai’i",hawaii island
37,"san martin jilotepeque, chimaltenango departme...",chimaltenango department
38,ethiopia,unknown
39,"piendamó, cauca department, colombia",cauca department
40,"medellin, colombia",unknown
41,"boquete growing region, western panama",western panama
42,"los santos, tarrazú, costa rica",tarraz
43,"guji zone, oromia region, southern ethiopia",oromia region
44,"guama village, kirinyaga county, kenya",kirinyaga county
45,"trujillo, valle del cauca, cauca department, c...",valle del cauca
46,"piendamó, cauca department, colombia",cauca department
47,"nyeri county, kenya",unknown
48,"trujillo, valle del cauca, cauca department, c...",valle del cauca
49,"santa cruz, ozolotepec, oaxaca, mexico",ozolotepec

In [44]:
# Pull Unique coffee_region Values
unique_regions = sorted(df_coffee_wrangle['coffee_region'].dropna().unique().tolist())
for region in unique_regions:
    print(region)

aberdare ridge
aceh province
acevedo
al hayma district
al kharijiyah district
alajuela
alajuela province
alta verapaz
alta verapaz department
amazonas region
ana sora district
antigua department
antioquia
antioquia department
apaneca growing region
arbegona
asia pacific
ataco
bench maji zone
bensa district
big island of hawaii
bolivia
boquete
boquete growing region
borena hagermariam district
brazil
brunca growing region
bule hora district
bure woreda
burundi
cajamarca
calda department
caldas
caldas department
cartago province
cauca
cauca department
central america
central colombia
central costa rica
central guatemala
central highlands
central kenya
central province
central valley
chaiyi
chiapas
chiapas state
chiayi
chiayi city
chiayi county
chimaltenango
chimaltenango department
chimborazo
chimborazo province
chiriqu
chiriqu province
chiriqui
chiriqui province
colombia
costa rica
cuilco
cundinamarca
cusco
democratic republic of the congo
dominican republic
east java
eastcentral colombia
eastern highlands
eastern province
eastern province kenya
ecuador
el progreso
el salvador
embu county
ethiopia
far western panama
fraijanes plateau growing region
gamo gofa zone
gatsibo district
gayo
gedeb
gedeb district
gedeo zone
guatemala
guatemala department
guji
guji growing region
guji zone
hambela wamena woreda
haraaz
hawaii
hawaii island
hayma dakhaliya
hoja blanca
honduras
huehuetenango
huehuetenango department
huehuetenango growing region
huila
huila department
imbabura province
indonesia
jalapa
java
jimma zone
juayua
kaffa province
karongi district
kau
keffa zone
kefichoshekicho zone
kenya
kerinci
kiambu county
kirinyaga county
kochere
kona
kona district
kona growing region
la argentina
la convencion province
la palma
lake atitlan
lake kivu
lintong growing region
loja
loja growing region
loja province
mandheling
manizales
mara region
marcala growing region
mbeya growing region
mbozi district
medellin
mexico
minas gerais
minas gerais state
muhinga province
muranga county
nario
nario department
near lahaina
nicaragua
north kona
north kona district
north kona growing district
north kona growing region
north sumatra
north sumatra province
northcentral guatemala
northcentral yemen
northern burundi
northern ecuador
northern province
northern sumatra
northern sumatra indonesia
northern tanzania
northwest colombia
northwestern el salvador
northwestern guatemala
nueva segovia region
nyeri county
nyeri growing region
oldeani growing region
oldeani region
oromia growing region
oromia region
oromia state
ozolotepec
panama
papua new guinea
parroquia santa rosa
pasco
pasco department
peru
pichincha
pichincha province
piedra candela
pijao village
pitalito
puna
puna district
quetzaltepec growing region
quindio
quindio department
renacimiento
risaralda
rulindo district
ruvuma region
rwanda
sabanilla de alajuela
sacatepequez department
san augustin
san ignacio
sanaa
sanaa governorate
santa ana department
santander department
saraguro
satipo province
sidama also sidamo growing area
sidama also sidamo growing region
sidama and yirgacheffe growing regions
sidama growing region
sidama province
sidama region
sidama zone
sidamo
sidamo and yirgacheffe growing regions
sidamo growing region
sidamo province
sidamo region
snnp region
snnpr
songwe region
south america
south central guatemala
south kivu province
south sulawesi
southcentral colombia
southcentral ethiopia
southcentral guatemala
southcentral kenya
southcentral sulawesi
southeastern brazil
southeastern el salvador
southeastern oahu
southern colombia
southern ecuador
southern ethiopia
southern india
southern province
southwest ethiopia
southwestern corner of the big island of hawaii
southwestern sulawesi
southwestern tanzania
sumatra
tabaconas
takengon
tarime
tarraz
tarraz growing region
tarrazu growing region
the democratic republic of the congo
tolima
tolima department
toraja growing region
turrubares
undisclosed
unknown
uraga
utcubamba province
valle de cauca department
valle del cauca
valle del cauca department
veracruz state
villa rica
volcan
volcan de san salvador
west and southwest of volcn bar
west arsi
west valley
western colombia
western ethiopia
western guji
western highlands
western highlands province
western kenya
western panama
western province
western rwanda
yirgacheffe
yirgacheffe growing region
yirgacheffe region of ethiopia

In [45]:
# Filter hawaii related regions
hawaii_candidates = [
    region for region in unique_regions
    if any(keyword in region for keyword in ['hawaii', 'kona', 'kau', 'puna', 'lahaina'])
]

In [46]:
hawaii_map = {variant: 'hawaii' for variant in hawaii_candidates}

In [48]:
list(hawaii_map.keys())

['big island of hawaii',
 'hawaii',
 'hawaii island',
 'kau',
 'kona',
 'kona district',
 'kona growing region',
 'near lahaina',
 'north kona',
 'north kona district',
 'north kona growing district',
 'north kona growing region',
 'puna',
 'puna district',
 'southwestern corner of the big island of hawaii']

In [49]:
# ID and then apply hawaii normlization
def normalize_hawaii(region):
    return hawaii_map.get(region, region)

df_coffee_wrangle['coffee_region'] = df_coffee_wrangle['coffee_region'].apply(normalize_hawaii)

In [50]:
# Work check
df_coffee_wrangle['coffee_region'].value_counts(dropna=False).head(30)

coffee_region
unknown                       486
southern ethiopia             237
southcentral kenya            159
hawaii                        133
western panama                123
oromia region                 113
southcentral ethiopia          72
cauca department               42
yirgacheffe growing region     29
gedeo zone                     28
ethiopia                       27
guji zone                      26
central kenya                  26
huila department               24
north sumatra province         22
guatemala                      22
sumatra                        19
colombia                       18
volcan                         14
northern sumatra               14
jimma zone                     14
boquete growing region         13
kenya                          13
chiriqui province              12
southern colombia              12
central highlands              12
quindio department             10
valle del cauca                10
far western panama              9
central valley                  9
Name: count, dtype: int64

In [51]:
# Spot Audit
df_coffee_wrangle[
    df_coffee_wrangle['coffee_region'].str.contains('hawaii|kona|kau|puna|lahaina', case=False, na=False)
    & (df_coffee_wrangle['coffee_region'] != 'hawaii')
][['coffee_origin', 'coffee_region']].head(30)

Empty DataFrame
Columns: [coffee_origin, coffee_region]
Index: []

##### Strip Suffix

In [52]:
# Strip suffixes
suffixes_to_strip = [
    'growing region',
    'province',
    'department',
    'zone',
    'district',
    'county',
    'state',
    'region'
]

In [53]:
# Stripping function
def strip_suffixes(region):
    if pd.isna(region):
        return region
    for suffix in suffixes_to_strip:
        if region.endswith(suffix):
            return region.replace(suffix, '').strip()
    return region

In [54]:
# Apply function
df_coffee_wrangle['coffee_region'] = df_coffee_wrangle['coffee_region'].apply(strip_suffixes)

In [55]:
# Work check
df_coffee_wrangle['coffee_region'].value_counts(dropna=False).head(30)

coffee_region
unknown                  486
southern ethiopia        237
southcentral kenya       159
hawaii                   133
western panama           123
oromia                   120
southcentral ethiopia     72
cauca                     47
yirgacheffe               30
gedeo                     28
guji                      28
huila                     27
ethiopia                  27
central kenya             26
north sumatra             24
guatemala                 23
sumatra                   19
boquete                   18
colombia                  18
valle del cauca           17
sidamo                    14
jimma                     14
northern sumatra          14
sidama                    14
volcan                    14
antioquia                 13
kenya                     13
chiriqui                  13
southern colombia         12
central highlands         12
Name: count, dtype: int64

In [56]:
# spot audit 
df_coffee_wrangle[df_coffee_wrangle['coffee_origin'].str.contains('growing region|province|department|zone|district|county|state|region', case=False, na=False)][['coffee_origin', 'coffee_region']].head(30)

                                        coffee_origin          coffee_region
0                        quindio department, colombia                unknown
1                        quindio department, colombia                unknown
3                     gimbo, kaffa province, ethiopia                  kaffa
4            sidamo growing region, southern ethiopia      southern ethiopia
7                          huila department, colombia                unknown
10           sidamo growing region, southern ethiopia      southern ethiopia
11  caicendonia, valle del cauca, cauca department...        valle del cauca
12               piendamo, cauca department, colombia                  cauca
13            mbozi district, songwe region, tanzania                 songwe
14      gedeb district, gedeo zone, southern ethiopia                  gedeo
15        guji zone, oromia region, southern ethiopia                 oromia
16     san josé de minas, pichincha province, ecuador              pichincha
18        guji growing region, south-central ethiopia  southcentral ethiopia
20           sidamo growing region, southern ethiopia      southern ethiopia
21              algeciras, huila department, colombia                  huila
22            santa maria, huila department, colombia                  huila
23      yirgacheffe growing region, southern ethiopia      southern ethiopia
24             caicedonia, cauca department, colombia                  cauca
25            kirinyaga district, south-central kenya     southcentral kenya
26       kaʻū growing region, hawai’i island, hawai’i                 hawaii
27       kaʻū growing region, hawai’i island, hawai’i                 hawaii
28                         huila department, colombia                unknown
32           sidamo growing region, southern ethiopia      southern ethiopia
33  bursa village, arbegona, sidama growing region...               arbegona
34       ka’u growing region, hawai’i island, hawai’i                 hawaii
35       ka’u growing region, hawai’i island, hawai’i                 hawaii
36             kona district, hawai’i island, hawai’i                 hawaii
37  san martin jilotepeque, chimaltenango departme...          chimaltenango
39               piendamó, cauca department, colombia                  cauca
41             boquete growing region, western panama         western panama

##### Strip Directional Prefixes

In [57]:
# Strip Directional Prefixes
def strip_directional_prefix(region):
    if pd.isna(region):
        return region
    directions = ['north', 'south', 'east', 'west', 'central']
    for d in directions:
        if region.startswith(d + ' '):
            return region.replace(d + ' ', '').strip()
    return region

In [58]:
# Apply the stripping
df_coffee_wrangle['coffee_region'] = df_coffee_wrangle['coffee_region'].apply(strip_directional_prefix)

In [59]:
# Work check
df_coffee_wrangle['coffee_region'].value_counts(dropna=False).head(30)

coffee_region
unknown                  486
southern ethiopia        237
southcentral kenya       159
hawaii                   133
western panama           123
oromia                   120
southcentral ethiopia     72
cauca                     47
sumatra                   43
kenya                     39
guatemala                 31
yirgacheffe               30
guji                      28
gedeo                     28
huila                     27
ethiopia                  27
colombia                  25
boquete                   18
valle del cauca           17
sidamo                    14
sidama                    14
jimma                     14
volcan                    14
northern sumatra          14
chiriqui                  13
antioquia                 13
southern colombia         12
highlands                 12
valley                    11
quindio                   11
Name: count, dtype: int64

In [60]:
# Spot audit
df_coffee_wrangle[
    df_coffee_wrangle['coffee_origin'].str.contains('south|north|east|west|central', case=False, na=False)
][['coffee_origin', 'coffee_region']].head(30)

                                        coffee_origin          coffee_region
4            sidamo growing region, southern ethiopia      southern ethiopia
10           sidamo growing region, southern ethiopia      southern ethiopia
14      gedeb district, gedeo zone, southern ethiopia                  gedeo
15        guji zone, oromia region, southern ethiopia                 oromia
17               alajuela, central valley, costa rica                 valley
18        guji growing region, south-central ethiopia  southcentral ethiopia
20           sidamo growing region, southern ethiopia      southern ethiopia
23      yirgacheffe growing region, southern ethiopia      southern ethiopia
25            kirinyaga district, south-central kenya     southcentral kenya
32           sidamo growing region, southern ethiopia      southern ethiopia
33  bursa village, arbegona, sidama growing region...               arbegona
41             boquete growing region, western panama         western panama
43        guji zone, oromia region, southern ethiopia                 oromia
50           sidamo growing region, southern ethiopia      southern ethiopia
62                 bench-maji zone, southern ethiopia      southern ethiopia
66            kirinyaga district, south-central kenya     southcentral kenya
70             boquete growing region, western panama         western panama
74        guji zone, oromia region, southern ethiopia                 oromia
76  yirgacheffe growing region, south-central ethi...  southcentral ethiopia
78           sidamo growing region, southern ethiopia      southern ethiopia
83        guji zone, oromia region, southern ethiopia                 oromia
84     bensa district, sidama zone, southern ethiopia                 sidama
85          nyeri growing region, south-central kenya     southcentral kenya
86           sidamo growing region, southern ethiopia      southern ethiopia
87  odo shakiso district, guji zone, southern ethi...                   guji
89                 bench-maji zone, southern ethiopia      southern ethiopia
90             boquete growing region, western panama         western panama
91             boquete growing region, western panama         western panama
92  hōlualoa, north kona growing region, hawai’i i...                 hawaii
97        guji zone, oromia region, southern ethiopia                 oromia

In [62]:
# Final directional prefixes
direction_strip_map = {
    'southern ethiopia': 'ethiopia',
    'southcentral ethiopia': 'ethiopia',
    'southcentral kenya': 'kenya',
    'southern colombia': 'colombia',
    'northern sumatra': 'sumatra',
    'western panama': 'panama',
    'central highlands': 'highlands',
    'central valley': 'unknown',
    'valley': 'unknown'
}

In [63]:
# Strip the remaining directional prefixes
def strip_directional_variant(region):
    return direction_strip_map.get(region, region)

df_coffee_wrangle['coffee_region'] = df_coffee_wrangle['coffee_region'].apply(strip_directional_variant)

In [64]:
# Work check
df_coffee_wrangle['coffee_region'].value_counts(dropna=False).head(30)

coffee_region
unknown               497
ethiopia              336
kenya                 198
hawaii                133
panama                124
oromia                120
sumatra                57
cauca                  47
colombia               37
guatemala              31
yirgacheffe            30
guji                   28
gedeo                  28
huila                  27
boquete                18
valle del cauca        17
sidama                 14
sidamo                 14
jimma                  14
volcan                 14
antioquia              13
chiriqui               13
highlands              12
quindio                11
chimaltenango          10
far western panama      9
valle de cauca          9
costa rica              9
huehuetenango           8
loja                    8
Name: count, dtype: int64

In [65]:
# Spot Aduit
df_coffee_wrangle[
    df_coffee_wrangle['coffee_origin'].str.contains('south|north|east|west|central', case=False, na=False)
][['coffee_origin', 'coffee_region']].head(30)

                                        coffee_origin coffee_region
4            sidamo growing region, southern ethiopia      ethiopia
10           sidamo growing region, southern ethiopia      ethiopia
14      gedeb district, gedeo zone, southern ethiopia         gedeo
15        guji zone, oromia region, southern ethiopia        oromia
17               alajuela, central valley, costa rica       unknown
18        guji growing region, south-central ethiopia      ethiopia
20           sidamo growing region, southern ethiopia      ethiopia
23      yirgacheffe growing region, southern ethiopia      ethiopia
25            kirinyaga district, south-central kenya         kenya
32           sidamo growing region, southern ethiopia      ethiopia
33  bursa village, arbegona, sidama growing region...      arbegona
41             boquete growing region, western panama        panama
43        guji zone, oromia region, southern ethiopia        oromia
50           sidamo growing region, southern ethiopia      ethiopia
62                 bench-maji zone, southern ethiopia      ethiopia
66            kirinyaga district, south-central kenya         kenya
70             boquete growing region, western panama        panama
74        guji zone, oromia region, southern ethiopia        oromia
76  yirgacheffe growing region, south-central ethi...      ethiopia
78           sidamo growing region, southern ethiopia      ethiopia
83        guji zone, oromia region, southern ethiopia        oromia
84     bensa district, sidama zone, southern ethiopia        sidama
85          nyeri growing region, south-central kenya         kenya
86           sidamo growing region, southern ethiopia      ethiopia
87  odo shakiso district, guji zone, southern ethi...          guji
89                 bench-maji zone, southern ethiopia      ethiopia
90             boquete growing region, western panama        panama
91             boquete growing region, western panama        panama
92  hōlualoa, north kona growing region, hawai’i i...        hawaii
97        guji zone, oromia region, southern ethiopia        oromia

##### Country to Unknown

In [67]:
# Convert any country in region list to unknown.
known_countries = sorted([
    'australia', 'brazil', 'burundi', 'canada', 'china', 'colombia', 'costa rica',
    'el salvador', 'england', 'ethiopia', 'guatemala', 'guinea', 'honduras',
    'hong kong', 'india', 'indonesia', 'japan', 'kenya', 'macao', 'mexico',
    'nicaragua', 'panama', 'peru', 'puerto rico', 'rwanda', 'south korea',
    'taiwan', 'tanzania', 'timor', 'united kingdom', 'united states', 'yemen'
])

def fallback_country_to_unknown(region):
    if region in known_countries:
        return 'unknown'
    return region
# Apply
df_coffee_wrangle['coffee_region'] = df_coffee_wrangle['coffee_region'].apply(fallback_country_to_unknown)

In [68]:
# Work check
df_coffee_wrangle['coffee_region'].value_counts(dropna=False).head(30)

coffee_region
unknown               1260
hawaii                 133
oromia                 120
sumatra                 57
cauca                   47
yirgacheffe             30
guji                    28
gedeo                   28
huila                   27
boquete                 18
valle del cauca         17
jimma                   14
sidama                  14
sidamo                  14
volcan                  14
chiriqui                13
antioquia               13
highlands               12
quindio                 11
chimaltenango           10
valle de cauca           9
far western panama       9
huehuetenango            8
loja                     8
pichincha                7
minas gerais             7
caldas                   7
tarraz                   6
tolima                   6
sanaa governorate        6
Name: count, dtype: int64

In [69]:
# Spot aduit
df_coffee_wrangle[
    df_coffee_wrangle['coffee_origin'].str.contains(
        'kenya|ethiopia|colombia|guatemala|panama|peru|mexico|rwanda|ecuador|indonesia|honduras|el salvador|brazil|yemen|tanzania|burundi|congo|costa rica|united states|united kingdom|china|india|japan|hong kong|macao|puerto rico|nicaragua|south korea|taiwan|guinea|canada|england|australia|timor',
        case=False, na=False)
][['coffee_origin', 'coffee_region']].head(30)

                                        coffee_origin    coffee_region
0                        quindio department, colombia          unknown
1                        quindio department, colombia          unknown
2                                  colombia; ethiopia          unknown
3                     gimbo, kaffa province, ethiopia            kaffa
4            sidamo growing region, southern ethiopia          unknown
5                                    panama; ethiopia          unknown
6                                      yunlin, taiwan          unknown
7                          huila department, colombia          unknown
8                                         cusco, peru          unknown
9                                      yunlin, taiwan          unknown
10           sidamo growing region, southern ethiopia          unknown
11  caicendonia, valle del cauca, cauca department...  valle del cauca
12               piendamo, cauca department, colombia            cauca
13            mbozi district, songwe region, tanzania           songwe
14      gedeb district, gedeo zone, southern ethiopia            gedeo
15        guji zone, oromia region, southern ethiopia           oromia
16     san josé de minas, pichincha province, ecuador        pichincha
17               alajuela, central valley, costa rica          unknown
18        guji growing region, south-central ethiopia          unknown
19              cerrado mineiro, minas gerais, brazil     minas gerais
20           sidamo growing region, southern ethiopia          unknown
21              algeciras, huila department, colombia            huila
22            santa maria, huila department, colombia            huila
23      yirgacheffe growing region, southern ethiopia          unknown
24             caicedonia, cauca department, colombia            cauca
25            kirinyaga district, south-central kenya          unknown
28                         huila department, colombia          unknown
29                                    rustiro, rwanda          unknown
30                            saraguro, loja, ecuador             loja
31                              jaén, cajamarca, peru        cajamarca

## 7. Wrangle Roaster Region

##### Hawaii Normalization

In [72]:
# Strip unicode from roaster_region
df_coffee_wrangle['roaster_region'] = df_coffee_wrangle['roaster_region'].apply(strip_unicode)

In [73]:
# Preview work
df_coffee_wrangle['roaster_region'].value_counts(dropna=False).head(30)

roaster_region
unknown           672
california        305
wisconsin         241
virginia          115
minnesota         113
hawaii            100
colorado           72
massachusetts      66
kansas             52
illinois           48
new jersey         37
montana            37
washington         36
new york           27
north carolina     26
connecticut        24
indiana            24
oregon             19
new hampshire      17
nevada             16
florida            14
ontario            12
vermont            10
ohio                9
georgia             9
oklahoma            8
texas               7
maine               7
missouri            6
hawaii island       6
Name: count, dtype: int64

In [74]:
# Work check
df_coffee_wrangle[['roaster_location', 'roaster_region']].head(50)

                 roaster_location  roaster_region
0            cleveland, tennessee       tennessee
1            cleveland, tennessee       tennessee
2         jersey city, new jersey      new jersey
3                 chia-yi, taiwan         unknown
4                 chia-yi, taiwan         unknown
5                taichung, taiwan         unknown
6                  yunlin, taiwan         unknown
7                 chia-yi, taiwan         unknown
8                 chia-yi, taiwan         unknown
9                  yunlin, taiwan         unknown
10                 taipei, taiwan         unknown
11             madison, wisconsin       wisconsin
12             madison, wisconsin       wisconsin
13             madison, wisconsin       wisconsin
14                  yilan, taiwan         unknown
15                  yilan, taiwan         unknown
16             madison, wisconsin       wisconsin
17      charlotte, north carolina  north carolina
18             madison, wisconsin       wisconsin
19               peoria, illinois        illinois
20             madison, wisconsin       wisconsin
21                floyd, virginia        virginia
22                 taipei, taiwan         unknown
23                 taipei, taiwan         unknown
24                 taipei, taiwan         unknown
25               taichung, taiwan         unknown
26  hilo, hawai’i island, hawai’i   hawaii island
27  hilo, hawai’i island, hawai’i   hawaii island
28          san diego, california      california
29                floyd, virginia        virginia
30            fort wayne, indiana         indiana
31            fort wayne, indiana         indiana
32            fort wayne, indiana         indiana
33            fort wayne, indiana         indiana
34                  hilo, hawai'i          hawaii
35                  hilo, hawai'i          hawaii
36                  hilo, hawai'i          hawaii
37              durango, colorado        colorado
38              norfolk, virginia        virginia
39           glendale, california      california
40           santa fe, new mexico      new mexico
41        los angeles, california      california
42                tulsa, oklahoma        oklahoma
43                 tainan, taiwan         unknown
44            baronett, wisconsin       wisconsin
45             madison, wisconsin       wisconsin
46             madison, wisconsin       wisconsin
47             madison, wisconsin       wisconsin
48             madison, wisconsin       wisconsin
49            fort wayne, indiana         indiana

In [75]:
# Pull Unique roaster_region Values
unique_roaster_regions = sorted(df_coffee_wrangle['roaster_region'].dropna().unique().tolist())
for region in unique_roaster_regions:
    print(region)

alaska
alberta
arizona
arkansas
big island of hawaii
british columbia
calfornia
california
californiaa
chiayi
colorado
connecticut
dc
florida
georgia
hawaii
hawaii island
idaho
illinois
indiana
iowa
kansas
kentucky
korea
louisiana
maine
maryland
massachusetts
maui
michigan
minnesota
mississippi
missouri
montana
nantou
nevada
new hampshire
new jersey
new mexico
new york
north carolina
oaxaca
ohio
oklahoma
ontario
oregon
pennsylvania
saskatchewan
satipo province
south dakota
sydney
taichung
taiwan
tennessee
texas
unknown
vermont
virginia
virginia and floyd
washington
wisconsin
wyoming
yunnan province

In [77]:
# Filter hawaii-related regions
hawaii_candidates = [
    region for region in unique_roaster_regions
    if any(keyword in region for keyword in ['hawaii', 'kona', 'kau', 'puna', 'lahaina', 'maui', 'big island'])
]

In [78]:
# Build hawaii normalization map
hawaii_map = {variant: 'hawaii' for variant in hawaii_candidates}
list(hawaii_map.keys())

['big island of hawaii', 'hawaii', 'hawaii island', 'maui']

In [79]:
# Apply hawaii normalization
def normalize_hawaii(region):
    return hawaii_map.get(region, region)

df_coffee_wrangle['roaster_region'] = df_coffee_wrangle['roaster_region'].apply(normalize_hawaii)

In [80]:
# Work check
df_coffee_wrangle['roaster_region'].value_counts(dropna=False).head(30)

roaster_region
unknown           672
california        305
wisconsin         241
virginia          115
hawaii            113
minnesota         113
colorado           72
massachusetts      66
kansas             52
illinois           48
new jersey         37
montana            37
washington         36
new york           27
north carolina     26
indiana            24
connecticut        24
oregon             19
new hampshire      17
nevada             16
florida            14
ontario            12
vermont            10
georgia             9
ohio                9
oklahoma            8
maine               7
texas               7
missouri            6
mississippi         5
Name: count, dtype: int64

In [81]:
# Spot Audit
df_coffee_wrangle[
    df_coffee_wrangle['roaster_region'].str.contains('hawaii|kona|kau|puna|lahaina|maui|big island', case=False, na=False)
    & (df_coffee_wrangle['roaster_region'] != 'hawaii')
][['roaster_location', 'roaster_region']].head(30)

Empty DataFrame
Columns: [roaster_location, roaster_region]
Index: []

##### Strip Suffixes

In [82]:
unique_roaster_regions = sorted(df_coffee_wrangle['roaster_region'].dropna().unique().tolist())
for region in unique_roaster_regions:
    print(region)

alaska
alberta
arizona
arkansas
british columbia
calfornia
california
californiaa
chiayi
colorado
connecticut
dc
florida
georgia
hawaii
idaho
illinois
indiana
iowa
kansas
kentucky
korea
louisiana
maine
maryland
massachusetts
michigan
minnesota
mississippi
missouri
montana
nantou
nevada
new hampshire
new jersey
new mexico
new york
north carolina
oaxaca
ohio
oklahoma
ontario
oregon
pennsylvania
saskatchewan
satipo province
south dakota
sydney
taichung
taiwan
tennessee
texas
unknown
vermont
virginia
virginia and floyd
washington
wisconsin
wyoming
yunnan province

In [83]:
roaster_region_map = {
    'virginia and floyd': 'virginia',
    'satipo province': 'satipo',
    'yunnan province': 'yunnan'
}

In [84]:
df_coffee_wrangle['roaster_region'] = df_coffee_wrangle['roaster_region'].replace(roaster_region_map)

In [85]:
df_coffee_wrangle['roaster_region'].value_counts(dropna=False).head(30)

roaster_region
unknown           672
california        305
wisconsin         241
virginia          116
hawaii            113
minnesota         113
colorado           72
massachusetts      66
kansas             52
illinois           48
new jersey         37
montana            37
washington         36
new york           27
north carolina     26
connecticut        24
indiana            24
oregon             19
new hampshire      17
nevada             16
florida            14
ontario            12
vermont            10
georgia             9
ohio                9
oklahoma            8
maine               7
texas               7
missouri            6
mississippi         5
Name: count, dtype: int64

##### Country to Unknown

In [86]:
# List of known countries
known_countries = sorted([
    'australia', 'brazil', 'burundi', 'canada', 'china', 'colombia', 'costa rica',
    'el salvador', 'england', 'ethiopia', 'guatemala', 'guinea', 'honduras',
    'hong kong', 'india', 'indonesia', 'japan', 'kenya', 'macao', 'mexico',
    'nicaragua', 'panama', 'peru', 'puerto rico', 'rwanda', 'south korea',
    'taiwan', 'tanzania', 'timor', 'united kingdom', 'united states', 'yemen',
    'korea'
])

In [87]:
# Convert to unknown
def fallback_country_to_unknown(region):
    if region in known_countries:
        return 'unknown'
    return region

df_coffee_wrangle['roaster_region'] = df_coffee_wrangle['roaster_region'].apply(fallback_country_to_unknown)

In [88]:
# Work check
df_coffee_wrangle['roaster_region'].value_counts(dropna=False).head(30)

roaster_region
unknown           675
california        305
wisconsin         241
virginia          116
hawaii            113
minnesota         113
colorado           72
massachusetts      66
kansas             52
illinois           48
new jersey         37
montana            37
washington         36
new york           27
north carolina     26
connecticut        24
indiana            24
oregon             19
new hampshire      17
nevada             16
florida            14
ontario            12
vermont            10
ohio                9
georgia             9
oklahoma            8
maine               7
texas               7
missouri            6
mississippi         5
Name: count, dtype: int64

##### Correct Spelling

In [89]:
# Look at the roaster region list
unique_roaster_regions = sorted(df_coffee_wrangle['roaster_region'].dropna().unique().tolist())
for region in unique_roaster_regions:
    print(region)

alaska
alberta
arizona
arkansas
british columbia
calfornia
california
californiaa
chiayi
colorado
connecticut
dc
florida
georgia
hawaii
idaho
illinois
indiana
iowa
kansas
kentucky
louisiana
maine
maryland
massachusetts
michigan
minnesota
mississippi
missouri
montana
nantou
nevada
new hampshire
new jersey
new mexico
new york
north carolina
oaxaca
ohio
oklahoma
ontario
oregon
pennsylvania
saskatchewan
satipo
south dakota
sydney
taichung
tennessee
texas
unknown
vermont
virginia
washington
wisconsin
wyoming
yunnan

In [91]:
# Correct spellings
spelling_map = {
    'calfornia': 'california',
    'californiaa': 'california',
    'dc': 'washington dc'
}
# Apply
df_coffee_wrangle['roaster_region'] = df_coffee_wrangle['roaster_region'].replace(spelling_map)

In [94]:
# Work check
unique_roaster_regions = sorted(df_coffee_wrangle['roaster_region'].dropna().unique().tolist())
for region in unique_roaster_regions:
    print(region)

alaska
alberta
arizona
arkansas
british columbia
california
chiayi
colorado
connecticut
florida
georgia
hawaii
idaho
illinois
indiana
iowa
kansas
kentucky
louisiana
maine
maryland
massachusetts
michigan
minnesota
mississippi
missouri
montana
nantou
nevada
new hampshire
new jersey
new mexico
new york
north carolina
oaxaca
ohio
oklahoma
ontario
oregon
pennsylvania
saskatchewan
satipo
south dakota
sydney
taichung
tennessee
texas
unknown
vermont
virginia
washington
washington dc
wisconsin
wyoming
yunnan

In [96]:
df_coffee_wrangle.head()

,coffee_name,total_score,roast_level,agtron_roast,price_usd,quantity_g,usd_per_gram,roaster_location,roaster_city,roaster_region,roaster_country,coffee_origin,coffee_city,coffee_region,coffee_country
0,colombia finca campo hermosa,94.0,light,82.0,29.99,226.8,$29.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,united states,"quindio department, colombia",quindio department,unknown,colombia
1,colombia finca la sirena mango co-ferment,94.0,light,87.0,22.99,226.8,$22.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,united states,"quindio department, colombia",quindio department,unknown,colombia
2,in bloom,94.0,light,88.0,25.0,250.0,$25.0 / 250.0g,"jersey city, new jersey",jersey city,new jersey,united states,colombia; ethiopia,colombia,unknown,colombia
3,ethiopia washed kaffa gimbo lot rich espresso,96.0,medium light,77.0,8.17,226.8,$8.17 / 226.8g,"chia-yi, taiwan",chia-yi,unknown,taiwan,"gimbo, kaffa province, ethiopia",gimbo,kaffa,ethiopia
4,ethiopia natural gute bona,95.0,medium light,78.0,13.07,226.8,$13.07 / 226.8g,"chia-yi, taiwan",chia-yi,unknown,taiwan,"sidamo growing region, southern ethiopia",sidamo growing region,unknown,unknown

## 8. Export

In [ ]:
# Export wrangled dataset
df_coffee_wrangle.to_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Top Rated Coffee\top_rated_coffee_wrangled.csv',
    index=False,
    encoding='utf-8'
)