# Top Coffee Dataset Initial Inspection/Cleaning

## Imports/Pathways

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# File Pathway
path = r"C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee"

In [3]:
# Import dataset
df_coffee = pd.read_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Top Rated Coffee\top-rated-coffee-edited.csv')

## Data Inspection
### Table of Contents
1. Overview
2. Missing Values
3. Duplicate Check
4. Spelling & Encoding Issues
5. Price and Measurement
6. Roast Level

### 1. Overview

In [4]:
# General check of first 10 rows
df_coffee.head()

,coffee_name,total_score,roaster_location,coffee_origin,roast_level,price_amount,price_unit,agtron_roast,price_per_ounce,origin_country
0,Colombia Finca Campo Hermosa,94.0,"Cleveland, Tennessee","Quindio Department, Colombia",Light,$29.99,8 ounces,82.0,29.990000,Colombia
1,Colombia Finca La Sirena Mango Co-Ferment,94.0,"Cleveland, Tennessee","Quindio Department, Colombia",Light,$22.99,8 ounces,87.0,22.990000,Colombia
2,In Bloom,94.0,"Jersey City, New Jersey",Colombia; Ethiopia,Light,$25.00,250 grams,88.0,0.881834,Ethiopia
3,Ethiopia Washed Kaffa Gimbo Lot Rich Espresso,96.0,"Chia-Yi, Taiwan","Gimbo, Kaffa Province, Ethiopia",Medium Light,NT $250,8 ounces,77.0,250.000000,Ethiopia
4,Ethiopia Natural Gute Bona,95.0,"Chia-Yi, Taiwan","Sidamo growing region, southern Ethiopia",Medium Light,NT $400,8 ounces,78.0,400.000000,Ethiopia

In [5]:
# Check the dataset shape
df_coffee.shape

(2215, 10)

In [6]:
# List all column headers
df_coffee.columns.tolist()

['coffee_name',
 'total_score',
 'roaster_location',
 'coffee_origin',
 'roast_level',
 'price_amount',
 'price_unit',
 'agtron_roast',
 'price_per_ounce',
 'origin_country']

In [7]:
# Check data types
df_coffee.dtypes

coffee_name          object
total_score         float64
roaster_location     object
coffee_origin        object
roast_level          object
price_amount         object
price_unit           object
agtron_roast        float64
price_per_ounce     float64
origin_country       object
dtype: object

In [8]:
# Descriptive statistics
df_coffee.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
coffee_name,2215,2027,Sumatra Tano Batak,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_score,2212.0,NaN,NaN,NaN,94.536618,0.758499,94.0,94.0,94.0,95.0,98.0
roaster_location,2215,255,"Madison, Wisconsin",214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
coffee_origin,2209,832,"Boquete growing region, western Panama",102,NaN,NaN,NaN,NaN,NaN,NaN,NaN
roast_level,2192,6,Medium Light,1263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_amount,2101,481,$20.00,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_unit,2096,90,12 ounces,839,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agtron_roast,2205.0,NaN,NaN,NaN,76.576417,16.54319,0.0,74.0,78.0,81.0,689.0
price_per_ounce,1956.0,NaN,NaN,NaN,110.145506,271.820033,0.282187,18.0,23.0,47.3125,5800.0
origin_country,1774,32,Ethiopia,545,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2. Missing Values

In [9]:
# Create a summary table of missing values
missing_count = df_coffee.isnull().sum()
missing_percent = (df_coffee.isnull().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percent
})

In [10]:
# Filter to show only columns with missing values
missing_summary = missing_summary[missing_summary['Missing Count'] > 0].sort_values(by='Missing Count', ascending=False)

missing_summary

                 Missing Count  Missing %
origin_country             441      19.91
price_per_ounce            259      11.69
price_unit                 119       5.37
price_amount               114       5.15
roast_level                 23       1.04
agtron_roast                10       0.45
coffee_origin                6       0.27
total_score                  3       0.14

A wide range of missing values but percentages are within reason

### 3. Duplicate Check

In [11]:
# Check for duplicate rows
df_coffee.duplicated().sum()

np.int64(0)

No duplicated rows found.

### 4. Spelling & Encoding Issues

With the assistance of Copilot and explaination I was able to determine all the text that are spelt odd.

In [12]:
# Step 1: Define a function to check for non-ASCII characters
def has_non_ascii(text):
    return any(ord(char) > 127 for char in str(text))
    
# Convert the input to string (in case it's not already)
# Loop through each character in the string
# If any character has a Unicode value > 127, it's non-ASCII (e.g. Ã, ñ, â€™)

In [13]:
# Step 2: Apply the function to key text columns to flag rows with weird characters
for col in ['coffee_name', 'roaster_location', 'coffee_origin', 'origin_country']:
    df_coffee[f'{col}_non_ascii'] = df_coffee[col].apply(has_non_ascii)
    
# Create a new column like 'coffee_name_non_ascii' with True/False values
# True means that row has non-ASCII characters in that column

In [14]:
# Step 3: Filter rows with any non-ASCII flags
df_encoding_issues = df_coffee[
    (df_coffee['coffee_name_non_ascii']) |
    (df_coffee['roaster_location_non_ascii']) |
    (df_coffee['coffee_origin_non_ascii']) |
    (df_coffee['origin_country_non_ascii'])
]

In [15]:
# Step 4: Set up a preview to see all flagged rows
# Configure pandas display settings for full visibility
pd.set_option('display.max_rows', None)           # Show all rows
pd.set_option('display.max_columns', None)        # Show all columns
pd.set_option('display.max_colwidth', None)       # Show full text in each cell
pd.set_option('display.expand_frame_repr', False) # Prevent line wrapping

# Original filtering logic
flagged = df_encoding_issues[
    df_encoding_issues['origin_country'].isna() | 
    (df_encoding_issues['origin_country'].str.len() < 4)
]

# Preview flagged rows with full visibility
flagged[['coffee_name', 'roaster_location', 'coffee_origin', 'origin_country']]

                                                    coffee_name                 roaster_location                                                              coffee_origin origin_country
26                                           Kaʻū Morning Glory    Hilo, Hawai’i Island, Hawai’i                               Kaʻū growing region, Hawai’i Island, Hawai’i            NaN
27                                          Kaʻū Yellow Bourbon    Hilo, Hawai’i Island, Hawai’i                               Kaʻū growing region, Hawai’i Island, Hawai’i            NaN
34                                        Ka’u Giant Maragogipe                    Hilo, Hawai'i                               Ka’u growing region, Hawai’i Island, Hawai’i            NaN
35                                             Ka’u Red Bourbon                    Hilo, Hawai'i                               Ka’u growing region, Hawai’i Island, Hawai’i            NaN
36                                                   Kona Bloom                    Hilo, Hawai'i                                     Kona District, Hawai’i Island, Hawai’i            NaN
64                                   Kona Tropical Punch Washed    Hilo, Hawai’i Island, Hawai’i                               Kona growing region, Hawai’i Island, Hawai'i            NaN
92                                Kona Geisha Champagne Natural    Hilo, Hawai’i Island, Hawai’i               Hōlualoa, North Kona growing region, Hawai’i Island, Hawai’i            NaN
107                                            Wai Meli Morning           Mountain View, Hawai'i                          Kona and Ka’u, Hawai’i; other undisclosed origins            NaN
149                                               Kahiko Orange                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
151                                                 Kona Orange                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
205                                      Orange Bourbon Natural                   Pahala, Hawaii                               Ka‘ū growing district, Big Island of Hawai’i            NaN
298                                          Kona Geisha Washed                     Hilo, Hawaii                     Holualoa, North Kona District, “Big Island” of Hawaiʻi            NaN
299                          Karen J Kona Red Bourbon Anaerobic                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
321                             Kona Espresso Special Selection                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
331                 Kona SL 34 Anaerobic Washed Kona Rainforest                     Hilo, Hawaii                                          South Kona, Big Island of Hawai’i            NaN
356           Kona Red Bourbon Anaerobic Washed Kona Rainforest                     Hilo, Hawaii                           South Kona growing region, Big Island of Hawai’i            NaN
361                                                   Kona Noir           Mountain View, Hawai’i                                      Holualoa, Kona, Big Island of Hawai’i            NaN
362                                        Laura’s Reserve SL34                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
364                                       Ka‘ū Cloud Maragogipe           Mountain View, Hawai'i                               Ka‘ū growing region, “Big Island” of Hawai’i            NaN
365                                            Geisha Champagne                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
366                       JN Farms Double Anaerobic Red Bourbon             Kihei, Maui, Hawai’i                                 Ka‘ū growing region, Big Island of Hawai’i            NaN
367                                       Ka‘ū Classic Peaberry  Pahala, “Big Island” of Hawai’i                             Ka‘ū growing district, "Big Island" of Hawai’i            NaN
368                                            100% Kona Typica                Holualoa, Hawai’i                                 Kona growing region, Big Island of Hawai’i            NaN
392                                Kona Mokka Champagne Natural                     Hilo, Hawaii                                 Kona growing region, Big Island of Hawai’i            NaN
404                                                Kona Pointu®                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
406                                    Karen J Kona Red Bourbon                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
437                                                 Kona Mocca®                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
462                                              Holiday Coffee                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
471                               Hawai’i Island Blend Espresso                     Hilo, Hawaii                       Ka‘ū and Kona growing regions, Big Island of Hawai’i            NaN
482                          Grand Champion Red Bourbon Natural                   Pahala, Hawaii                               Ka'u growing district, Big Island of Hawai’i            NaN
506                                                     Kona K7      Hilo, Big Island of Hawai'i                                      Holualoa, Kona, Big Island of Hawai’i            NaN
518                                             SL34 Dark Roast                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
539                                     Ka‘ū Malolactic Natural      Hilo, Big Island of Hawai’i                                 Ka‘ū growing region, Big Island of Hawai’i            NaN
552                                                Kona Classic                     Hilo, Hawaii                                 Kona growing region, Big Island of Hawai’i            NaN
553                              Hawai’i Ka‘ū Champagne Natural                     Hilo, Hawaii                                 Ka‘ū growing region, Big Island of Hawai’i            NaN
571                              Ka‘ū JN Farms Malolactic Honey      Hilo, Big Island of Hawai’i                                 Ka‘ū growing region, Big Island of Hawai’i            NaN
588                                    Ka‘u Red Catuai Peaberry                     Hilo, Hawaii                                 Ka‘u growing region, Big Island of Hawai’i            NaN
595                                        Laura’s Reserve SL34                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
613                                         Ka’u Tropical Punch           Minneapolis, Minnesota                                 Ka'u growing region, Big Island of Hawai’i            NaN
660                                            Kona Extra Fancy              Lincoln, California                               Kona growing region, “Big Island” of Hawai’i            NaN
684                                                      Kahiko                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
690                                                   Kona Noir            Mountain View, Hawaii                                      Holualoa, Kona, Big Island of Hawai’i            NaN
691                                            Kona Red Bourbon            Mountain View, Hawaii                                      Holualoa, Kona, Big Island of Hawai’i            NaN
708                                    Karen J Kona Red Bourbon                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
728                       Hawaii Ka‘ū Bourbon Anaerobic Natural           Minneapolis, Minnesota                                 Ka‘ū growing region, Big Island of Hawai’i            NaN
743                    Kona SL34 Champagne Natural Uluwehi Farm           Minneapolis, Minnesota                                      Holualoa, Kona, Big Island of Hawai’i            NaN
764                                       Kona Natural Espresso                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
784                                  Ka‘ū Tropical Punch Washed           Minneapolis, Minnesota                                                Ka‘ū, Big Island of Hawai’i            NaN
787                    Kona SL34 Champagne Natural Uluwehi Farm           Minneapolis, Minnesota                                      Holualoa, Kona, Big Island of Hawai’i            NaN
789                                         Ka‘ū Lactic Natural           Minneapolis, Minnesota                                                Ka‘ū, Big Island of Hawai‘i            NaN
804                 Kona Bourbon Champagne Natural Uluwehi Farm           Minneapolis, Minnesota                                      Holualoa, Kona, Big Island of Hawai’i            NaN
807                                              Pointu Laurina                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
811                                           Ka’u Classic Dark                  Pahala, Hawai'i                                 Ka’u growing region, Big Island of Hawai’i            NaN
830                                     Monarch Estate Pacamara                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
831   Uluwehi Farm Kona SL34 Yeast-Fermentation Washed Peaberry           Minneapolis, Minnesota                       Holualoa, Kona growing region, Big Island of Hawai’i            NaN
832                                            Ka’u IPA Natural           Minneapolis, Minnesota                                 Ka’u growing region, Big Island of Hawai’i            NaN
837                  Karen J Kona Red Bourbon Natural Anaerobic                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
864                                  Kona Tropical Punch Washed           Minneapolis, Minnesota                                                Kona, Big Island of Hawai’i            NaN
865                              Ka’u Bourbon Champagne Natural           Minneapolis, Minnesota                                 Ka’u growing region, Big Island of Hawai’i            NaN
876                                     Natural Ka’u Maragogipe           Mountain View, Hawai’i                                 Ka’u growing region, Big Island of Hawai’i            NaN
887                                                    Espresso                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
889                                                 Kona Mocca®                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
890                                    Karen J Kona Red Bourbon                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
895                                              Holiday Coffee                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
898                                        Laura’s Reserve SL34                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
900                          Puna Arakawa Estate Lactic Natural           Minneapolis, Minnesota                                  Kurtistown, Puna, “Big Island” of Hawai’i            NaN
901                            100% Kona Bourbon Pointu Laurina                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
948                                       Kona Red Wine Process           Minneapolis, Minnesota                                                Kona, Big Island of Hawai’i            NaN
966                                          Kona Lactic Washed           Minneapolis, Minnesota                                                Kona, Big Island of Hawai’i            NaN
1003                           Kona Maragogype Peaberry Natural                   Pahala, Hawaii                                 Kona growing region, Big Island of Hawai’i            NaN
1045                                    Kona Maragogype Natural           Minneapolis, Minnesota                                      Kainaliu, Kona, Big Island of Hawai’i            NaN
1056                                       Kona SL34 Sweet Spot                 Holualoa, Hawaii                                 Kona growing region, Big Island of Hawai’i            NaN
1058                                                Kona Mocca®                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
1060                                              Kona Peaberry           Mountain View, Hawai’i                                 Kona growing region, Big Island of Hawai’i            NaN
1062                                                       SL28            Captain Cook, Hawai’i                       North Kona growing district, “Big Island” of Hawai’i            NaN
1063                                     Bourbon Pointu Natural                Holualoa, Hawai’i                                 Kona growing region, Big Island of Hawai’i            NaN
1074                                          Kona Uluwehi SL34           Minneapolis, Minnesota                                      Holualoa, Kona, Big Island of Hawai’i            NaN
1093                                            Ka’u Pink Honey           Minneapolis, Minnesota                                       Ka'u District, Big Island of Hawai’i            NaN
1094                                 Kona Maragogype Pink Honey           Minneapolis, Minnesota                             Kainaliu, Kona District, Big Island of Hawai’i            NaN
1111                                        Ka’u Yellow Bourbon            Mountain View, Hawaii                                 Ka’u growing region, Big Island of Hawai'i            NaN
1136             Kona Red Bourbon Anaerobic Washed Uluwehi Farm           Minneapolis, Minnesota                                      Holualoa, Kona, Big Island of Hawai’i            NaN
1138                                     Honey Typica Anaerobic            Captain Cook, Hawai’i                       North Kona growing district, “Big Island” of Hawai’i            NaN
1139                                                     Geisha             Captain Cook, Hawaii                       North Kona growing district, “Big Island” of Hawai’i            NaN
1153                                                Kona Mocca®                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
1154                                             Holiday Coffee                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai’i            NaN
1173                              Hawai’i Puna Anaerobic Washed           Minneapolis, Minnesota                                 Puna growing region, Big Island of Hawai’i            NaN
1196                                       Laura’s Reserve SL34                Holualoa, Hawai’i             Holualoa, North Kona growing district, “Big Island” of Hawai'i            NaN
1201                               Yellow Caturra (special lot)                     Ka'u, Hawaii                                 Ka’u growing region, Big island of Hawai’i            NaN
1202          Hawai’i Kilauea Volcano Yeast Fermentation Washed           Minneapolis, Minnesota                                                Puna, Big Island of Hawai’i            NaN
1203                            Kona Pink Honey Black Rock Farm           Minneapolis, Minnesota                                                Kona, Big Island of Hawai’i            NaN
1224                                  Ka’u Red Caturra Peaberry              Kihei, Maui, Hawaii                                   Wood Valley, Ka’u, Big Island of Hawai’i            NaN
1234                          Kilauea Volcano Champagne Natural           Minneapolis, Minnesota                              Volcano, Puna District, Big Island of Hawai’i            NaN
1259                               Kona Classic Black Rock Farm           Minneapolis, Minnesota                                                Kona, Big Island of Hawai’i            NaN
1267                                      Ka’u Giant Maragogipe           Mountain View, Hawai'i                                 Ka’u growing region, Big Island of Hawai'i            NaN
1382                                     Ka’u Champagne Natural           Minneapolis, MInnesota                                 Ka'u growing region, Big Island of Hawai'i            NaN
1383                                              Monarch Gesha           San Rafael, California             Holualoa, North Kona growing district, “Big Island” of Hawai'i            NaN
1776                              Ecuador “Mama Kilya” Espresso             Taoyuan City, Taiwan                                                                   Ecuador.            NaN
1779                       Panama Lino Esmeralda Geisha Natural             La Jolla, California                      Cañas Verdes, Boquete growing region, western Panama.            NaN
1805                                Sillvia Solkiln N2 Level 95    Pu’Er, Yunnan Province, China                                           Silla Del Pando, Volcan, Panama.            NaN
1806                             Sweet Maria’s Acatenango Gesha    Pu’Er, Yunnan Province, China                              Acatenango growing region, central Guatemala.            NaN
1831                              Esmeralda Leon Natural Geisha             La Jolla, California                      Cañas Verdes, Boquete growing region, western Panama.            NaN
1834                                      Laura’s Reserve SL-28                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawaii.            NaN
1855                                  High Mountain Red Bourbon                 Holualoa, Hawaii             Holualoa, North Kona growing district, “Big Island” of Hawaii.            NaN
1867                                      Ethiopia Chele’ Lektu             Jackson, MIssissippi                             Yirgacheffe growing region, southern Ethiopia.            NaN
1871                                               Perci N2 L39    Pu’Er, Yunnan Province, China                                           Silla Del Pando, Volcan, Panama.            NaN

### 5. Price and Measurement

I want to make price/weigth to be consistant and here I'll identify what I have to work with.

In [16]:
# Preview unique price formats — check for currency and unit inconsistencies
df_coffee['price_unit'].unique()

array(['8 ounces', '250 grams', '4 ounces', '12 ounces', '200 grams',
       '100 grams', '10 ounces', ' 12 ounces', '227 grams', '170 grams',
       '113 grams', '50 grams', '20 grams', '6 ounces', '120 grams', nan,
       '125 grams', '225 grams', '.8 ounces', '220 grams', '7 ounces',
       '150 ml bottle', '150 grams', '10 ounces (sold as a set of 3',
       '455 grams', '454 grams', '230 grams', '12ounces',
       '4 ounces (sold only as a two-pack)', '240 grams', '310 grams',
       '175 grams', '200g', '14 ounces', '16 ounces', '60 grams',
       '10 capsules', '5.5 ounces', '105 grams', ' 227 grams',
       ' 8 ounces', '227g', '10.5 ounces', '150-gram packet',
       '70 grams; $200.00', '300 grams', '5 ounces', '160-ml bottle',
       '12-ounce bottle', '150-gram tin', '375 ml. flask', '115 grams',
       '8-ounce can', 'can', '50 ounces', '150 ml. bottle',
       '8 ounces (currently on sale for $36.76)', '12 ounces ($79.00',
       ' 7 ounces', '18 grams', '4 ounces; limited availability',
       '21 grams', '8 ounces*', '340 grams', '225 gram', '8.4-ounce can',
       '25.4-ounce bottle (seasonal)', '320 grams', '500 grams',
       '75 grams', ' 16 ounces', '125 g', '16 fluid ounces', '3.5 ounces',
       '5.3 ounces', '12 ounces.', '12 onces', '250 grams (8.8 oz.)',
       '250 grams (8.8 oz)', '16 ounces (454 grams)',
       '8 ounces (227 grams)', '1 kg. (2.2 lbs.)', '8 oz.', '12 oz.',
       '10 oz.', '16 oz.', '32 oz.', ' 500 g. (17.6 oz.)',
       ' 250 g. (8.8 oz.)', ' 16 oz.', ' 12 oz.'], dtype=object)

With this information I inputted into Copilot to id all the unquie characters.

In [17]:
# Extract currency symbols or codes using regex
df_coffee['price_currency'] = df_coffee['price_amount'].str.extract(
    r'(NTD\$|NT\$|USD\$|US\$|CAD\$|AUD\$|HKD\$|HK\$|KRW\$|KRW|RMB\$|CNY\$|IDR\$|¥|£|€|\$)',
    expand=False
)

In [18]:
# Count unique currency formats
currency_counts = df_coffee['price_currency'].value_counts(dropna=False)
currency_counts

price_currency
$       2030
NaN      132
NT$       31
KRW       10
£          6
¥          4
NTD$       1
KRW$       1
Name: count, dtype: int64

In [19]:
# Measurement Units
# Extract unit keyword from each string
df_coffee['unit_keyword'] = (
    df_coffee['price_unit']
    .astype(str)
    .str.lower()
    .str.extract(r'(gram|g|kg|ounce|oz|lb|pound|ml|fl oz|fluid ounce|capsule|can|bottle)')
)

In [20]:
# Count frequency of each unit keyword
unit_keyword_counts = df_coffee['unit_keyword'].value_counts(dropna=False)
unit_keyword_counts

unit_keyword
ounce          1726
gram            333
NaN             120
oz               17
ml                6
g                 5
capsule           5
can               1
fluid ounce       1
kg                1
Name: count, dtype: int64

In [21]:
# Count unique units formats
unit_counts = df_coffee['price_unit'].value_counts(dropna=False)
unit_counts

price_unit
12 ounces                                  839
8 ounces                                   522
4 ounces                                   165
NaN                                        119
16 ounces                                   88
227 grams                                   71
200 grams                                   68
100 grams                                   50
250 grams                                   37
6 ounces                                    36
10 ounces                                   36
225 grams                                   24
150 grams                                   13
230 grams                                    9
12 oz.                                       8
20 grams                                     7
125 grams                                    6
7 ounces                                     6
454 grams                                    5
 12 ounces                                   5
10 capsules                                  5
220 grams                                    5
50 grams                                     4
8 oz.                                        4
113 grams                                    4
150 ml bottle                                3
250 grams (8.8 oz.)                          3
18 grams                                     2
14 ounces                                    2
300 grams                                    2
120 grams                                    2
10 ounces (sold as a set of 3                2
60 grams                                     2
175 grams                                    2
4 ounces (sold only as a two-pack)           2
12 ounces.                                   2
455 grams                                    1
170 grams                                    1
.8 ounces                                    1
200g                                         1
12ounces                                     1
5.5 ounces                                   1
310 grams                                    1
10.5 ounces                                  1
150-gram packet                              1
70 grams; $200.00                            1
5 ounces                                     1
160-ml bottle                                1
12-ounce bottle                              1
150-gram tin                                 1
375 ml. flask                                1
115 grams                                    1
8-ounce can                                  1
can                                          1
105 grams                                    1
 227 grams                                   1
 8 ounces                                    1
227g                                         1
240 grams                                    1
 7 ounces                                    1
12 ounces ($79.00                            1
8 ounces (currently on sale for $36.76)      1
150 ml. bottle                               1
50 ounces                                    1
4 ounces; limited availability               1
21 grams                                     1
8 ounces*                                    1
320 grams                                    1
500 grams                                    1
75 grams                                     1
 16 ounces                                   1
340 grams                                    1
225 gram                                     1
8.4-ounce can                                1
25.4-ounce bottle (seasonal)                 1
5.3 ounces                                   1
3.5 ounces                                   1
16 fluid ounces                              1
125 g                                        1
250 grams (8.8 oz)                           1
16 ounces (454 grams)                        1
8 ounces (227 grams)                         1
12 onces                                     1
1 kg. (2.2 lbs.)                             1
10 oz.                                       1
16 oz.                                       1
32 oz.                                       1
 500 g. (17.6 oz.)                           1
 250 g. (8.8 oz.)                            1
 16 oz.                                      1
 12 oz.                                      1
Name: count, dtype: int64

### 6. Roast Level

In [22]:
# Preview roast level categories — check for casing and punctuation variants
df_coffee['roast_level'].value_counts()

roast_level
Medium Light    1263
Light            630
Medium           244
Medium Dark       49
Dark               5
Very Dark          1
Name: count, dtype: int64

The format for roast_levels are fine

## Data Cleaning
### Table of Contents
1. Spelling and Encoding Issues 
2. Price and Measurement Unit Format Inconsistencies
3. Dropping Columns
4. Dropping Rows with Missing Vital Data
5. Missing values
6. Export

### 1. Spelling and Encoding Issues

In [23]:
# Create a clean copy of rows with missing or suspicious origin_country values
df_encoding_issues = df_coffee[df_coffee['origin_country'].isna() | (df_coffee['origin_country'].str.len() < 4)].copy()

In [24]:
import re

def normalize_encoding(text):
    if pd.isna(text):
        return text
    # Remove all apostrophe-like characters and quotes
    text = re.sub(r"[ʻ’‘'\"“”]", "", text)
    # Replace dashes and ellipses
    text = text.replace("–", "-").replace("…", "...").strip()
    return text

In [25]:
# Apply normalization to all relevant columns
for col in ['coffee_name', 'roaster_location', 'coffee_origin', 'origin_country']:
    df_encoding_issues[col] = df_encoding_issues[col].apply(normalize_encoding)

In [26]:
# Assign 'United States' for Hawaii-related origins
hawaii_keywords_raw = [
    'hawaii', 'hawai’i', 'big island', 'kona', 'ka’u', 'puna',
    'holualoa', 'mountain view', 'captain cook', 'kurtistown', 'kainaliu'
]

hawaii_keywords = [normalize_encoding(k).lower() for k in hawaii_keywords_raw]


def infer_hawaii_country(origin, current_country):
    if pd.notna(current_country):
        return current_country
    if pd.isna(origin):
        return current_country
    origin_lower = origin.lower()
    if any(keyword in origin_lower for keyword in hawaii_keywords):
        return 'United States'
    return current_country

In [27]:
# Extract known country names from origin string
known_countries = [
    'panama', 'guatemala', 'ethiopia', 'kenya', 'nicaragua', 'ecuador', 'costa rica'
]

def extract_country_from_origin(origin, current_country):
    if pd.notna(current_country):
        return current_country
    if pd.isna(origin):
        return current_country
    origin_lower = origin.lower()
    for country in known_countries:
        if country in origin_lower:
            return country.title()
    return current_country

In [28]:
# Infer 'United States' from roaster location if origin is missing
def infer_from_roaster_location(roaster, current_country):
    if pd.notna(current_country):
        return current_country
    if pd.isna(roaster):
        return current_country
    if 'hawaii' in roaster.lower() or 'hawai’i' in roaster.lower():
        return 'United States'
    return current_country

In [29]:
# Apply all inference functions in order of priority
df_encoding_issues['origin_country'] = df_encoding_issues.apply(
    lambda row: infer_hawaii_country(
        row['coffee_origin'],
        extract_country_from_origin(
            row['coffee_origin'],
            infer_from_roaster_location(row['roaster_location'], row['origin_country'])
        )
    ),
    axis=1
)

In [30]:
# Update original DataFrame with cleaned origin_country values
df_coffee.loc[df_encoding_issues.index, 'origin_country'] = df_encoding_issues['origin_country']

In [31]:
# Work check and preview cleaned rows by index
df_coffee.loc[df_encoding_issues.index, ['coffee_name', 'roaster_location', 'coffee_origin', 'origin_country']]

                                                         coffee_name                      roaster_location                                                                              coffee_origin origin_country
26                                                Kaʻū Morning Glory         Hilo, Hawai’i Island, Hawai’i                                               Kaʻū growing region, Hawai’i Island, Hawai’i  United States
27                                               Kaʻū Yellow Bourbon         Hilo, Hawai’i Island, Hawai’i                                               Kaʻū growing region, Hawai’i Island, Hawai’i  United States
34                                             Ka’u Giant Maragogipe                         Hilo, Hawai'i                                               Ka’u growing region, Hawai’i Island, Hawai’i  United States
35                                                  Ka’u Red Bourbon                         Hilo, Hawai'i                                               Ka’u growing region, Hawai’i Island, Hawai’i  United States
36                                                        Kona Bloom                         Hilo, Hawai'i                                                     Kona District, Hawai’i Island, Hawai’i  United States
64                                        Kona Tropical Punch Washed         Hilo, Hawai’i Island, Hawai’i                                               Kona growing region, Hawai’i Island, Hawai'i  United States
92                                     Kona Geisha Champagne Natural         Hilo, Hawai’i Island, Hawai’i                               Hōlualoa, North Kona growing region, Hawai’i Island, Hawai’i  United States
106                                                       Pueo Blend                         Hilo, Hawai'i                                                    Guatemala and other undisclosed origins  United States
107                                                 Wai Meli Morning                Mountain View, Hawai'i                                          Kona and Ka’u, Hawai’i; other undisclosed origins  United States
149                                                    Kahiko Orange                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
151                                                      Kona Orange                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
205                                           Orange Bourbon Natural                        Pahala, Hawaii                                               Ka‘ū growing district, Big Island of Hawai’i  United States
246                              Colombia Los Nogales Yellow Bourbon                          Osaka, Japan                                                                                        NaN            NaN
298                                               Kona Geisha Washed                          Hilo, Hawaii                                     Holualoa, North Kona District, “Big Island” of Hawaiʻi  United States
299                               Karen J Kona Red Bourbon Anaerobic                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
321                                  Kona Espresso Special Selection                      Holualoa, Hawaii                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
331                      Kona SL 34 Anaerobic Washed Kona Rainforest                          Hilo, Hawaii                                                          South Kona, Big Island of Hawai’i  United States
356                Kona Red Bourbon Anaerobic Washed Kona Rainforest                          Hilo, Hawaii                                           South Kona growing region, Big Island of Hawai’i  United States
361                                                        Kona Noir                Mountain View, Hawai’i                                                      Holualoa, Kona, Big Island of Hawai’i  United States
362                                             Laura’s Reserve SL34                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
364                                            Ka‘ū Cloud Maragogipe                Mountain View, Hawai'i                                               Ka‘ū growing region, “Big Island” of Hawai’i  United States
365                                                 Geisha Champagne                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
366                            JN Farms Double Anaerobic Red Bourbon                  Kihei, Maui, Hawai’i                                                 Ka‘ū growing region, Big Island of Hawai’i  United States
367                                            Ka‘ū Classic Peaberry       Pahala, “Big Island” of Hawai’i                                             Ka‘ū growing district, "Big Island" of Hawai’i  United States
368                                                 100% Kona Typica                     Holualoa, Hawai’i                                                 Kona growing region, Big Island of Hawai’i  United States
392                                     Kona Mokka Champagne Natural                          Hilo, Hawaii                                                 Kona growing region, Big Island of Hawai’i  United States
404                                                     Kona Pointu®                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
406                                         Karen J Kona Red Bourbon                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
437                                                      Kona Mocca®                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
462                                                   Holiday Coffee                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
471                                    Hawai’i Island Blend Espresso                          Hilo, Hawaii                                       Ka‘ū and Kona growing regions, Big Island of Hawai’i  United States
482                               Grand Champion Red Bourbon Natural                        Pahala, Hawaii                                               Ka'u growing district, Big Island of Hawai’i  United States
506                                                          Kona K7           Hilo, Big Island of Hawai'i                                                      Holualoa, Kona, Big Island of Hawai’i  United States
518                                                  SL34 Dark Roast                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
539                                          Ka‘ū Malolactic Natural           Hilo, Big Island of Hawai’i                                                 Ka‘ū growing region, Big Island of Hawai’i  United States
552                                                     Kona Classic                          Hilo, Hawaii                                                 Kona growing region, Big Island of Hawai’i  United States
553                                   Hawai’i Ka‘ū Champagne Natural                          Hilo, Hawaii                                                 Ka‘ū growing region, Big Island of Hawai’i  United States
571                                   Ka‘ū JN Farms Malolactic Honey           Hilo, Big Island of Hawai’i                                                 Ka‘ū growing region, Big Island of Hawai’i  United States
585                         Ethiopia Sidama Karamo Anaerobic Natural                      Bozeman, Montana                                             Sidamo growing region, south-central Ethiopia.       Ethiopia
588                                         Ka‘u Red Catuai Peaberry                          Hilo, Hawaii                                                 Ka‘u growing region, Big Island of Hawai’i  United States
595                                             Laura’s Reserve SL34                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
613                                              Ka’u Tropical Punch                Minneapolis, Minnesota                                                 Ka'u growing region, Big Island of Hawai’i  United States
660                                                 Kona Extra Fancy                   Lincoln, California                                               Kona growing region, “Big Island” of Hawai’i  United States
684                                                           Kahiko                      Holualoa, Hawaii                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
690                                                        Kona Noir                 Mountain View, Hawaii                                                      Holualoa, Kona, Big Island of Hawai’i  United States
691                                                 Kona Red Bourbon                 Mountain View, Hawaii                                                      Holualoa, Kona, Big Island of Hawai’i  United States
708                                         Karen J Kona Red Bourbon                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
728                            Hawaii Ka‘ū Bourbon Anaerobic Natural                Minneapolis, Minnesota                                                 Ka‘ū growing region, Big Island of Hawai’i  United States
743                         Kona SL34 Champagne Natural Uluwehi Farm                Minneapolis, Minnesota                                                      Holualoa, Kona, Big Island of Hawai’i  United States
764                                            Kona Natural Espresso                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
784                                       Ka‘ū Tropical Punch Washed                Minneapolis, Minnesota                                                                Ka‘ū, Big Island of Hawai’i  United States
787                         Kona SL34 Champagne Natural Uluwehi Farm                Minneapolis, Minnesota                                                      Holualoa, Kona, Big Island of Hawai’i  United States
789                                              Ka‘ū Lactic Natural                Minneapolis, Minnesota                                                                Ka‘ū, Big Island of Hawai‘i  United States
804                      Kona Bourbon Champagne Natural Uluwehi Farm                Minneapolis, Minnesota                                                      Holualoa, Kona, Big Island of Hawai’i  United States
807                                                   Pointu Laurina                      Holualoa, Hawaii                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
811                                                Ka’u Classic Dark                       Pahala, Hawai'i                                                 Ka’u growing region, Big Island of Hawai’i  United States
830                                          Monarch Estate Pacamara                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
831        Uluwehi Farm Kona SL34 Yeast-Fermentation Washed Peaberry                Minneapolis, Minnesota                                       Holualoa, Kona growing region, Big Island of Hawai’i  United States
832                                                 Ka’u IPA Natural                Minneapolis, Minnesota                                                 Ka’u growing region, Big Island of Hawai’i  United States
837                       Karen J Kona Red Bourbon Natural Anaerobic                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
839                            El Salvador Las Veraneras Red Bourbon                       Floyd, Virginia                                                          Apaneca Ilamatepec mountain range            NaN
851                                          Bedhatu Jibicho Natural                    Madison, Wisconsin                                                       Gedeb District, Gedeo Zone, southern            NaN
864                                       Kona Tropical Punch Washed                Minneapolis, Minnesota                                                                Kona, Big Island of Hawai’i  United States
865                                   Ka’u Bourbon Champagne Natural                Minneapolis, Minnesota                                                 Ka’u growing region, Big Island of Hawai’i  United States
876                                          Natural Ka’u Maragogipe                Mountain View, Hawai’i                                                 Ka’u growing region, Big Island of Hawai’i  United States
887                                                         Espresso                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
889                                                      Kona Mocca®                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
890                                         Karen J Kona Red Bourbon                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
895                                                   Holiday Coffee                      Holualoa, Hawaii                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
898                                             Laura’s Reserve SL34                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
900                               Puna Arakawa Estate Lactic Natural                Minneapolis, Minnesota                                                  Kurtistown, Puna, “Big Island” of Hawai’i  United States
901                                 100% Kona Bourbon Pointu Laurina                      Holualoa, Hawaii                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
948                                            Kona Red Wine Process                Minneapolis, Minnesota                                                                Kona, Big Island of Hawai’i  United States
966                                               Kona Lactic Washed                Minneapolis, Minnesota                                                                Kona, Big Island of Hawai’i  United States
974                                                   Espresso Blend               New Taipei City, Taiwan                                                                              Not disclosed            NaN
1003                                Kona Maragogype Peaberry Natural                        Pahala, Hawaii                                                 Kona growing region, Big Island of Hawai’i  United States
1045                                         Kona Maragogype Natural                Minneapolis, Minnesota                                                      Kainaliu, Kona, Big Island of Hawai’i  United States
1056                                            Kona SL34 Sweet Spot                      Holualoa, Hawaii                                                 Kona growing region, Big Island of Hawai’i  United States
1058                                                     Kona Mocca®                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
1060                                                   Kona Peaberry                Mountain View, Hawai’i                                                 Kona growing region, Big Island of Hawai’i  United States
1062                                                            SL28                 Captain Cook, Hawai’i                                       North Kona growing district, “Big Island” of Hawai’i  United States
1063                                          Bourbon Pointu Natural                     Holualoa, Hawai’i                                                 Kona growing region, Big Island of Hawai’i  United States
1074                                               Kona Uluwehi SL34                Minneapolis, Minnesota                                                      Holualoa, Kona, Big Island of Hawai’i  United States
1093                                                 Ka’u Pink Honey                Minneapolis, Minnesota                                                       Ka'u District, Big Island of Hawai’i  United States
1094                                      Kona Maragogype Pink Honey                Minneapolis, Minnesota                                             Kainaliu, Kona District, Big Island of Hawai’i  United States
1111                                             Ka’u Yellow Bourbon                 Mountain View, Hawaii                                                 Ka’u growing region, Big Island of Hawai'i  United States
1136                  Kona Red Bourbon Anaerobic Washed Uluwehi Farm                Minneapolis, Minnesota                                                      Holualoa, Kona, Big Island of Hawai’i  United States
1138                                          Honey Typica Anaerobic                 Captain Cook, Hawai’i                                       North Kona growing district, “Big Island” of Hawai’i  United States
1139                                                          Geisha                  Captain Cook, Hawaii                                       North Kona growing district, “Big Island” of Hawai’i  United States
1153                                                     Kona Mocca®                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
1154                                                  Holiday Coffee                     Holualoa, Hawai’i                             Holualoa, North Kona growing district, “Big Island” of Hawai’i  United States
1173                                   Hawai’i Puna Anaerobic Washed                Minneapolis, Minnesota                                                 Puna growing region, Big Island of Hawai’i  United States

The remaining 84 rows are due to missing data which will be handed in the missing data section.

### 2. Price and Measurement Unit Format Inconsistencies

#### Price Inconsistencies

In [32]:
# Normalize and clean the various price units
def clean_currency(value):
    if pd.isna(value):
        return np.nan
    value = str(value).strip().lower()
    mapping = {
        '$': 'USD',
        'usd $': 'USD',
        'us $': 'USD',
        'cad $': 'CAD',
        'aud $': 'AUD',
        'nt$': 'TWD',
        'ntd$': 'TWD',
        'nt $': 'TWD',
        'hkd $': 'HKD',
        'hk $': 'HKD',
        'krw': 'KRW',
        'krw $': 'KRW',
        'rmb $': 'CNY',
        'cny $': 'CNY',
        '¥': 'JPY',
        '£': 'GBP',
        'idr $': 'IDR'
    }
    return mapping.get(value, value.upper())

In [33]:
# Create a new column, price_currency_clean with normalized currencies.
df_coffee['price_currency_clean'] = df_coffee['price_currency'].apply(clean_currency)

In [34]:
# Exchange rates table to USD
exchange_rates = {
    'USD': 1.0,
    'TWD': 0.03268,
    'KRW': 0.0007042,
    'GBP': 1.3407,
    'JPY': 0.006638,
    'AUD': 0.6518,
    'CAD': 0.7125,
    'CNY': 0.1404,
    'IDR': 0.00006031,
    'HKD': 0.1287
}

In [35]:
# Step 1: Extract Currency Symbol or Lab
# Pulls the currency prefix from each string
df_coffee['price_currency_raw'] = (
    df_coffee['price_amount']
    .astype(str)
    .str.extract(r'^([^\d\s]+(?:\s*\$)?)')  # Captures things like $, NT $, €, ¥, etc.
)

In [36]:
# Step 2: Normalize Currency Labels
# Uses existing clean_currency() function to map the messy labels
df_coffee['price_currency_clean'] = df_coffee['price_currency_raw'].apply(clean_currency)

In [37]:
# Extract Numeric Price
df_coffee['price_amount_clean'] = (
    df_coffee['price_amount']
    .astype(str)
    .str.extract(r'(\d+\.?\d*)')
    .astype(float)
)

In [38]:
# Currency conversation
df_coffee['price_usd'] = df_coffee.apply(
    lambda row: row['price_amount_clean'] * exchange_rates.get(row['price_currency_clean'], np.nan),
    axis=1
)

In [39]:
# price_usd had more than 2 decimals so I fixed this
df_coffee['price_usd'] = df_coffee['price_usd'].round(2)

In [40]:
# Work check
df_coffee[['price_amount', 'price_currency_raw', 'price_currency_clean', 'price_amount_clean', 'price_usd']].head(10)

  price_amount price_currency_raw price_currency_clean  price_amount_clean  price_usd
0      $29.99                   $                  USD               29.99      29.99
1      $22.99                   $                  USD               22.99      22.99
2      $25.00                   $                  USD               25.00      25.00
3      NT $250               NT $                  TWD              250.00       8.17
4      NT $400               NT $                  TWD              400.00      13.07
5      $39.00                   $                  USD               39.00      39.00
6      NT $800               NT $                  TWD              800.00      26.14
7      NT $350               NT $                  TWD              350.00      11.44
8      NT $300               NT $                  TWD              300.00       9.80
9      NT $600               NT $                  TWD              600.00      19.61

#### Measurement  Inconsistencies

In [41]:
# Cean and Standardize Unit Labels
def clean_unit(value):
    if pd.isna(value):
        return np.nan
    value = str(value).lower().strip()
    if 'gram' in value or value == 'g':
        return 'g'
    elif 'kg' in value:
        return 'kg'
    elif 'ounce' in value or value == 'oz':
        return 'oz'
    elif 'lb' in value or 'pound' in value:
        return 'lb'
    else:
        return np.nan

df_coffee['price_unit_clean'] = df_coffee['price_unit'].apply(clean_unit)

In [42]:
unit_conversion_to_g = {
    'g': 1,
    'kg': 1000,
    'oz': 28.3495,
    'lb': 453.592
}

In [43]:
# Extract Numeric Quantity
df_coffee['unit_quantity'] = (
    df_coffee['price_unit']
    .astype(str)
    .str.extract(r'(\d+\.?\d*)')[0]
    .astype(float)
)

In [44]:
# Convert All to Grams
def convert_to_g(row):
    unit = row['price_unit_clean']
    qty = row['unit_quantity']
    factor = unit_conversion_to_g.get(unit)
    return qty * factor if factor and qty else np.nan

df_coffee['quantity_g'] = df_coffee.apply(convert_to_g, axis=1)

In [45]:
# Keep it to two decimals
df_coffee['quantity_g'] = df_coffee['quantity_g'].round(2)

In [46]:
# Work check
df_coffee[['price_usd', 'price_unit', 'price_unit_clean', 'unit_quantity', 'quantity_g']].head(10)

   price_usd price_unit price_unit_clean  unit_quantity  quantity_g
0      29.99   8 ounces               oz            8.0       226.8
1      22.99   8 ounces               oz            8.0       226.8
2      25.00  250 grams                g          250.0       250.0
3       8.17   8 ounces               oz            8.0       226.8
4      13.07   8 ounces               oz            8.0       226.8
5      39.00   8 ounces               oz            8.0       226.8
6      26.14   4 ounces               oz            4.0       113.4
7      11.44   8 ounces               oz            8.0       226.8
8       9.80   4 ounces               oz            4.0       113.4
9      19.61   4 ounces               oz            4.0       113.4

In [47]:
# Create a column combining the price (USD) with measurement (gram)
df_coffee['usd_per_gram'] = (
    '$' + df_coffee['price_usd'].round(2).astype(str)
    + ' / ' + df_coffee['quantity_g'].round(2).astype(str)
    + 'g'
)

In [48]:
# Work check
df_coffee[['price_usd', 'quantity_g', 'usd_per_gram']].head(10)

   price_usd  quantity_g     usd_per_gram
0      29.99       226.8  $29.99 / 226.8g
1      22.99       226.8  $22.99 / 226.8g
2      25.00       250.0   $25.0 / 250.0g
3       8.17       226.8   $8.17 / 226.8g
4      13.07       226.8  $13.07 / 226.8g
5      39.00       226.8   $39.0 / 226.8g
6      26.14       113.4  $26.14 / 113.4g
7      11.44       226.8  $11.44 / 226.8g
8       9.80       113.4    $9.8 / 113.4g
9      19.61       113.4  $19.61 / 113.4g

### 3. Dropping Columns

In [49]:
# Dropping price_per_unit and origin_country
df_coffee.drop(columns=['price_per_ounce', 'origin_country'], inplace=True)

The columns price_per_ounce and origin_country were dropped to streamline the dataset. price_per_ounce was removed because a more robust column was created that standardizes both currency and measurement units. origin_country was dropped due to incomplete coverage and will be reconstructed from coffee_origin using a structured extraction pipeline in a later step.

In [50]:
# Work check
print(df_coffee.columns.tolist())

['coffee_name', 'total_score', 'roaster_location', 'coffee_origin', 'roast_level', 'price_amount', 'price_unit', 'agtron_roast', 'coffee_name_non_ascii', 'roaster_location_non_ascii', 'coffee_origin_non_ascii', 'origin_country_non_ascii', 'price_currency', 'unit_keyword', 'price_currency_clean', 'price_currency_raw', 'price_amount_clean', 'price_usd', 'price_unit_clean', 'unit_quantity', 'quantity_g', 'usd_per_gram']

Both price_per_unit and origin_country were dropped.

### 4. Dropping Rows with Missing Vital Data

In [51]:
df_coffee.isna().sum().sort_values(ascending=False)

quantity_g                    154
price_unit_clean              154
price_usd                     146
price_currency                132
unit_keyword                  120
unit_quantity                 120
price_unit                    119
price_amount_clean            116
price_amount                  114
roast_level                    23
agtron_roast                   10
coffee_origin                   6
total_score                     3
coffee_name                     0
roaster_location                0
origin_country_non_ascii        0
coffee_name_non_ascii           0
roaster_location_non_ascii      0
coffee_origin_non_ascii         0
price_currency_raw              0
price_currency_clean            0
usd_per_gram                    0
dtype: int64

From this list I will go through each column to see if there are rows to be dropped

#### total_score

In [52]:
# Seeing if rows can be dropped due to missing critical fields
df_coffee[df_coffee['total_score'].isna()]

               coffee_name  total_score        roaster_location coffee_origin  roast_level price_amount price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g usd_per_gram
2212  Elm City House Blend          NaN  New Haven, Connecticut           NaN         Dark          NaN        NaN          43.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN  $nan / nang
2213          Vienna Roast          NaN  Lake Tahoe, California           NaN  Medium Dark          NaN        NaN          44.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN  $nan / nang
2214  Natural Moka – Green          NaN            Maui, Hawaii           NaN          NaN          NaN        NaN           NaN                   True                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN  $nan / nang

Retaining: None. 
Dropping: 2212-2214. missing critical fields; entry lacks usable data and appears to be a shell row.

In [53]:
# Drop rows 2212–2214
df_coffee = df_coffee[df_coffee['total_score'].notna()]

In [54]:
# Work check on the dropped rows
df_coffee[df_coffee['total_score'].isna()]

Empty DataFrame
Columns: [coffee_name, total_score, roaster_location, coffee_origin, roast_level, price_amount, price_unit, agtron_roast, coffee_name_non_ascii, roaster_location_non_ascii, coffee_origin_non_ascii, origin_country_non_ascii, price_currency, unit_keyword, price_currency_clean, price_currency_raw, price_amount_clean, price_usd, price_unit_clean, unit_quantity, quantity_g, usd_per_gram]
Index: []

Successfully dropped: rows 2212-2214

#### coffee_origins

In [55]:
# Updated missing value count_v1
df_coffee.isna().sum()[df_coffee.isna().sum() > 0]

coffee_origin           3
roast_level            22
price_amount          111
price_unit            116
agtron_roast            9
price_currency        129
unit_keyword          117
price_amount_clean    113
price_usd             143
price_unit_clean      151
unit_quantity         117
quantity_g            151
dtype: int64

There are only 3 of 6 coffee_origin rows missing data after the last rows were dropped. Note to self - repeat missing value check after rows are dropped

In [56]:
# Seeing if rows can be dropped due to missing critical fields
df_coffee[df_coffee['coffee_origin'].isna()]

                              coffee_name  total_score   roaster_location coffee_origin roast_level price_amount price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g    usd_per_gram
246   Colombia Los Nogales Yellow Bourbon         94.0       Osaka, Japan           NaN       Light      $28.00   150 grams          86.0                  False                       False                    False                     False              $         gram                  USD                  $                28.0       28.0                g          150.0       150.0  $28.0 / 150.0g
2210                      Finca La Tacita         95.0       Boise, Idaho           NaN         NaN          NaN        NaN           NaN                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN     $nan / nang
2211                 Ethiopia Yirgacheffe         94.0  Fairbanks, Alaska           NaN         NaN          NaN        NaN           NaN                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN     $nan / nang

Retaining: row 246 - sufficient data across key fields for analysis and conversion.
Dropping: row(s) 2210, 2211 - missing critical fields; entry lacks usable data and appears to be a shell row.

In [57]:
# Drop rows 2210 & 2211
df_coffee = df_coffee.drop([2210, 2211])

In [58]:
# Work check on the dropped rows
df_coffee[df_coffee['coffee_origin'].isna()]

                             coffee_name  total_score roaster_location coffee_origin roast_level price_amount price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g    usd_per_gram
246  Colombia Los Nogales Yellow Bourbon         94.0     Osaka, Japan           NaN       Light      $28.00   150 grams          86.0                  False                       False                    False                     False              $         gram                  USD                  $                28.0       28.0                g          150.0       150.0  $28.0 / 150.0g

Successfully dropped: rows 2210 & 2211
Retained: row 246

In [59]:
# Updated missing value count_v2
df_coffee.isna().sum()[df_coffee.isna().sum() > 0]

coffee_origin           1
roast_level            20
price_amount          109
price_unit            114
agtron_roast            7
price_currency        127
unit_keyword          115
price_amount_clean    111
price_usd             141
price_unit_clean      149
unit_quantity         115
quantity_g            149
dtype: int64

#### roast_level

In [60]:
# Seeing if rows can be dropped due to missing critical fields
df_coffee[df_coffee['roast_level'].isna()]

                                       coffee_name  total_score           roaster_location                                   coffee_origin roast_level price_amount                    price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g       usd_per_gram
243    Brazil Ipanema Premier Cru Cherry Cold Drip         94.0              Yilan, Taiwan                   Southern Minas Gerais, Brazil         NaN      NT $200                 150 ml bottle           0.0                  False                       False                    False                     False              $           ml                  TWD               NT $              200.00       6.54              NaN          150.0         NaN       $6.54 / nang
277                     Euphora Plumeria Cold Brew         94.0             Taipei, Taiwan                                      Costa Rica         NaN       NT 200                 150 ml bottle           NaN                  False                       False                    False                     False            NaN           ml                   NT                 NT              200.00        NaN              NaN          150.0         NaN        $nan / nang
278      Colombia El Paraiso Lychee Rose Cold Drip         94.0              Yilan, Taiwan            Piendamó, Cauca Department, Colombia         NaN       NT 240                 150 ml bottle           NaN                  False                       False                     True                     False            NaN           ml                   NT                 NT              240.00        NaN              NaN          150.0         NaN        $nan / nang
738                 Esmeralda Estate Panama Geisha         94.0            London, England          Boquete growing region, western Panama         NaN          £50                   10 capsules           0.0                  False                       False                    False                     False              £      capsule                  GBP                  £               50.00      67.04              NaN           10.0         NaN      $67.04 / nang
941                                  Yemen Lot 106         96.0       San Jose, California      Al Hayma region, Sana’a Governorate, Yemen         NaN      $45.00                       4 ounces           0.0                  False                       False                     True                     False              $        ounce                  USD                  $               45.00      45.00               oz            4.0      113.40     $45.0 / 113.4g
943                                  Yemen Al Wadi         94.0       San Jose, California       Al Wadi region, Sana’a Governorate, Yemen         NaN      $32.00                       4 ounces           0.0                  False                       False                     True                     False              $        ounce                  USD                  $               32.00      32.00               oz            4.0      113.40     $32.0 / 113.4g
997       Brazil Ipanema Golden Edition C26 Lychee         94.0              Yilan, Taiwan                                 Ipanema, Brazil         NaN      NT $200                 160-ml bottle           0.0                  False                       False                    False                     False              $           ml                  TWD               NT $              200.00       6.54              NaN          160.0         NaN       $6.54 / nang
998                     Ethiopia Mormora Cold Brew         94.0        Spokane, Washington              Guji Zone, Oromia Region, Ethiopia         NaN       $5.50                12-ounce bottle           0.0                  False                       False                    False                     False              $        ounce                  USD                  $                5.50       5.50               oz           12.0      340.19     $5.5 / 340.19g
1044        Bourbon Barrel Aged Ethiopia Cold Brew         94.0       Glendale, California   Yirgacheffe growing region, southern Ethiopia         NaN      $11.00                  375 ml. flask           0.0                  False                       False                    False                     False              $           ml                  USD                  $               11.00      11.00              NaN          375.0         NaN       $11.0 / nang
1157                Esmeralda Estate Panama Geisha         94.0            London, England          Boquete growing region, western Panama         NaN          £45                   10 capsules           0.0                  False                       False                    False                     False              £      capsule                  GBP                  £               45.00      60.33              NaN           10.0         NaN      $60.33 / nang
1249                    Guji Uraga Nitro Cold Brew         94.0           Denver, Colorado     Guji Zone, Oromia region, southern Ethiopia         NaN       $3.99                    8-ounce can           0.0                  False                       False                    False                     False              $        ounce                  USD                  $                3.99       3.99               oz            8.0      226.80     $3.99 / 226.8g
1250                          Kamoini Black Coffee         94.0  San Francisco, California       Nyeri growing region, south-central Kenya         NaN       $4.00                            can           0.0                  False                       False                    False                     False              $          can                  USD                  $                4.00       4.00              NaN            NaN         NaN        $4.0 / nang
1251                Ethiopia Nano Challa Cold Brew         94.0       Carbondale, Colorado              Jimma Zone, Oromia State, Ethiopia         NaN      $18.99                      50 ounces           0.0                  False                       False                    False                     False              $        ounce                  USD                  $               18.99      18.99               oz           50.0     1417.48  $18.99 / 1417.48g
1252  Brazil Ipanema Black Edition A-41 Red Cherry         94.0              Yilan, Taiwan                                 Ipanema, Brazil         NaN      NT $200                150 ml. bottle           0.0                  False                       False                    False                     False              $           ml                  TWD               NT $              200.00       6.54              NaN          150.0         NaN       $6.54 / nang
1266                Esmeralda Estate Panama Geisha         94.0            London, England          Boquete growing region, western Panama         NaN       £50.00                   10 capsules           0.0                  False                       False                    False                     False              £      capsule                  GBP                  £               50.00      67.04              NaN           10.0         NaN      $67.04 / nang
1360             Cup of Excellence Rwanda Champion         94.0            London, England      Karongi District, Western Province, Rwanda         NaN       £40.50                   10 capsules           0.0                  False                       False                    False                     False              £      capsule                  GBP                  £               40.50      54.30              NaN           10.0         NaN       $54.3 / nang
1472                Esmeralda Estate Panama Geisha         94.0            London, England          Boquete growing region, western Panama         NaN          £50                   10 capsules           NaN                  False                       False                    False                     False              £      capsule                  GBP                  £               50.00      67.04              NaN           10.0         NaN      $67.04 / nang
1486                             Reserve Cold Brew         94.0       Martinez, California                                        Tanzania         NaN      $12.00   25.4-ounce bottle (seasonal)           NaN                  False                       False                    False                     False              $        ounce                  USD                  $               12.00      12.00               oz           25.4      720.08    $12.0 / 720.08g
1887               Ready-to-Drink Coffee Cold Brew         94.0    Raleigh, North Carolina  Yirgacheffe growing region, southern Ethiopia.         NaN       $6.00                16 fluid ounces           NaN                  False                       False                    False                     False              $  fluid ounce                  USD                  $                6.00       6.00               oz           16.0      453.59     $6.0 / 453.59g
2040           Colombia Granja La Esperanza Geisha         96.0     San Rafael, California            Trujillo, Valle del Cauca, Colombia.         NaN      $32.00                       8 ounces           0.0                  False                       False                    False                     False              $        ounce                  USD                  $               32.00      32.00               oz            8.0      226.80     $32.0 / 226.8g

Retained: All rows currently selected. Dropped: None

#### agtron_roast

In [61]:
# Seeing if rows can be dropped due to missing critical fields
df_coffee[df_coffee['agtron_roast'].isna()]

                                    coffee_name  total_score         roaster_location                                   coffee_origin roast_level price_amount                    price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g     usd_per_gram
277                  Euphora Plumeria Cold Brew         94.0           Taipei, Taiwan                                      Costa Rica         NaN       NT 200                 150 ml bottle           NaN                  False                       False                    False                     False            NaN           ml                   NT                 NT              200.00        NaN              NaN          150.0         NaN      $nan / nang
278   Colombia El Paraiso Lychee Rose Cold Drip         94.0            Yilan, Taiwan            Piendamó, Cauca Department, Colombia         NaN       NT 240                 150 ml bottle           NaN                  False                       False                     True                     False            NaN           ml                   NT                 NT              240.00        NaN              NaN          150.0         NaN      $nan / nang
1472             Esmeralda Estate Panama Geisha         94.0          London, England          Boquete growing region, western Panama         NaN          £50                   10 capsules           NaN                  False                       False                    False                     False              £      capsule                  GBP                  £               50.00      67.04              NaN           10.0         NaN    $67.04 / nang
1474         Red Bourbon Honey Cold Brew Coffee         94.0    San Diego, California             Valle de Cauca Department, Colombia       Light       $4.65                  8.4-ounce can           NaN                  False                       False                    False                     False              $        ounce                  USD                  $                4.65       4.65               oz            8.4      238.14  $4.65 / 238.14g
1486                          Reserve Cold Brew         94.0     Martinez, California                                        Tanzania         NaN      $12.00   25.4-ounce bottle (seasonal)           NaN                  False                       False                    False                     False              $        ounce                  USD                  $               12.00      12.00               oz           25.4      720.08  $12.0 / 720.08g
1634                        Single-Origin Nitro         95.0       Madison, Wisconsin                                        Ethiopia       Light       $3.49                      12 ounces           NaN                  False                       False                    False                     False              $        ounce                  USD                  $                3.49       3.49               oz           12.0      340.19  $3.49 / 340.19g
1887            Ready-to-Drink Coffee Cold Brew         94.0  Raleigh, North Carolina  Yirgacheffe growing region, southern Ethiopia.         NaN       $6.00                16 fluid ounces           NaN                  False                       False                    False                     False              $  fluid ounce                  USD                  $                6.00       6.00               oz           16.0      453.59   $6.0 / 453.59g

Retained: All rows currently selected. Dropped: None

#### price_amount & price_unit

In [62]:
# Setting to max because I want to scan the rows manually
pd.set_option('display.max_rows', None)

# Seeing if rows can be dropped due to missing critical fields
df_coffee[df_coffee[['price_unit', 'price_amount']].isna().any(axis=1)]

                                                    coffee_name  total_score             roaster_location                                                              coffee_origin   roast_level                      price_amount price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g   usd_per_gram
124                 Costa Rica Red Java Honey Finca Los Pinitos         95.0    Charlotte, North Carolina                                       Alajuela, Central Valley, Costa Rica         Light                           $29.00         NaN          88.0                  False                       False                    False                     False              $          NaN                  USD                  $               29.00      29.00              NaN            NaN         NaN   $29.0 / nang
862            Ethiopia Tamiru Tadesse Tesema Anaerobic Natural         95.0                Yilan, Taiwan                                   Sidama growing region, southern Ethiopia  Medium Light      NA (available in store only)        NaN          78.0                  False                       False                    False                     False            NaN          NaN                   NA                 NA                 NaN        NaN              NaN            NaN         NaN    $nan / nang
885            Colombia Huila Finca Monteblanco Rodrigo Sanchez         94.0             Hong Kong, China                                                 Palestina, Huila, Colombia  Medium Light                               NaN        NaN          78.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1309              Ecuador Eugenioides Natural Finca Perla Negra         94.0       Minneapolis, Minnesota                                                Pichincha, northern Ecuador  Medium Light                               NaN        NaN          73.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1343      Best of Panama GNEP-01 Elida Geisha Green Tip Natural         97.0        Branford, Connecticut                                     Boquete growing region, western Panama  Medium Light  See website for more information        NaN          73.0                  False                       False                    False                     False            NaN          NaN                  SEE                See                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1605                         Colombia La Palma Y El Tucan Gesha         94.0        San Diego, California                                  Cundinamarca Department, central Colombia         Light                               NaN        NaN          84.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1780                                     Ethiopia Sidama Akrabi         94.0               Lake, Michigan                             Guji Zone, Sidama Province, southern Ethiopia.  Medium Light                           $15.00         NaN          71.0                  False                       False                    False                     False              $          NaN                  USD                  $               15.00      15.00              NaN            NaN         NaN   $15.0 / nang
1835                                       Semeon Abay Ethiopia         95.0           Lee, Massachusetts                                          Southern and/or western Ethiopia.         Light                               NaN        NaN          84.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1860                                     Ethiopia Homacho Waeno         95.0          Oakland, California       Aleta Wondo, Sidama (also Sidamo) growing region, southern Ethiopia.  Medium Light                               NaN        NaN          75.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1861                        Colombia Granja Esperanza Gesha AAA         95.0          Oakland, California                                  Valle del Cauca growing region, Colombia.  Medium Light                               NaN        NaN          76.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1866                                          Kenya AA Giakanja         94.0   Yorktown Heights, New York                                    Nyeri County, Central Highlands, Kenya.  Medium Light                               NaN        NaN          71.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
1931                                             Lennette Kenya         94.0         La Jolla, California                                 Nyeri growing region, south-central Kenya.  Medium Light                           $17.99         NaN          68.0                  False                       False                    False                     False              $          NaN                  USD                  $               17.99      17.99              NaN            NaN         NaN  $17.99 / nang
1985                    La Esmeralda Mario Carnaval 2012 Panama         96.0         Acton, Massachusetts                                     Boquete growing region, western Panama         Light                               NaN        NaN          86.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2109                                            Sulawesi Toraja         94.0        Kansas City, Missouri                    Toraja growing region, southwestern Sulawesi, Indonesia        Medium                               NaN        NaN          71.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2110                              Indonesia Blue Batak Peaberry         94.0         La Jolla, California                                                Northern Sumatra, Indonesia   Medium Dark                               NaN        NaN          53.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2111                                        Romance by Paradise         94.0            Ramsey, Minnesota                        Southwestern Ethiopia; northern Sumatra, Indonesia.         Light                               NaN        NaN          89.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2112                  Ethiopia Washed Yirgacheffe, Koke Grade 1         97.0         Taoyuan City, Taiwan            Yirgacheffe growing region, Sidamo Province, southern Ethiopia.  Medium Light                               NaN        NaN          78.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2113                                               Kenya AA Top         96.0         Taoyuan City, Taiwan                                                                      Kenya        Medium                               NaN        NaN          64.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2114                              Costa Rica Finca Cerro Palado         95.0               Topeka, Kansas                                Tarrazu growing region, central Costa Rica.  Medium Light                               NaN        NaN          77.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2115                                  Ethiopia Yirgacheffe Koke         94.0     Arlington, Massachusetts            Yirgacheffe growing region, Sidamo Province, southern Ethiopia.        Medium                               NaN        NaN          70.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2116                                          Kenya Gichathaini         94.0            Chicago, Illinois                                 Nyeri growing region, south-central Kenya.  Medium Light                               NaN        NaN          82.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2117                                               La Esmeralda         95.0         Acton, Massachusetts                                     Boquete growing region, western Panama  Medium Light                               NaN        NaN          82.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2118                                         Sumatra Danau Toba         94.0            Ramsey, Minnesota                                                Northern Sumatra, Indonesia  Medium Light                               NaN        NaN          73.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2119                                              Kenya Githiru         95.0        San Dimas, California                                                        South-central Kenya  Medium Light                               NaN        NaN          75.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2120                                Panama Elida Estate Natural         95.0               Topeka, Kansas                                     Boquete growing region, western Panama  Medium Light                               NaN        NaN          79.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2121                    Fair Trade Organic Ethiopia Yirgacheffe         94.0           Waterbury, Vermont            Yirgacheffe growing region, Sidamo Province, southern Ethiopia.        Medium                               NaN        NaN          61.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2122               Hacienda La Esmeralda Special Mario Carnaval         96.0               Topeka, Kansas                                     Boquete growing region, western Panama         Light                               NaN        NaN          99.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2123                                     Panama El Burro Estate         94.0            Longwood, Florida                                     Boquete growing region, western Panama        Medium                               NaN        NaN          73.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2124                                               Ka’u Bourbon         95.0               Pahala, Hawaii  Ka'u growing district, southwestern corner of the "Big Island" of Hawaii.        Medium                               NaN        NaN          69.0                   True                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2125                           Kenya Peaberry Thika Gethumbwini         96.0           Madison, Wisconsin                                                        South-central Kenya         Light                               NaN        NaN          90.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2126                                            Burundi Kinyovu         95.0          St. Louis, Missouri                                                 Kayanza Province, Burundi.  Medium Light                               NaN        NaN          77.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2127                                      Bonsai Blend Espresso         94.0          Seattle, Washington                                                             Not disclosed.   Medium Dark                               NaN        NaN          47.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2128                    Ethiopia Yirgacheffe Beloya Selection 8         95.0           Lee, Massachusetts            Yirgacheffe growing region, Sidamo Province, southern Ethiopia.         Light                               NaN        NaN          91.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2129                                        Romance by Paradise         95.0            Ramsey, Minnesota                                                        Yemen; undisclosed.        Medium                               NaN        NaN          66.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2130                                          Kenya AA Gachatha         95.0        Branford, Connecticut                                                       South-central Kenya.        Medium                               NaN        NaN          58.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2131                                     “Kona Sweet” 100% Kona         97.0             Holualoa, Hawaii                                                           Holualoa, Hawaii         Light                               NaN        NaN          83.0                   True                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang
2132                             Kenya Ndiara Full Flavor Roast         96.0         Acton, Massachusetts                                  Kirinyaga growing district, Central Kenya  Medium Light                               NaN        NaN          75.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN    $nan / nang

Retained: All rows. Dropped: None. I manually looked through the short list. I could see that all important data values were present, but either the price_amount and/or price_unit data was missing, so all these rows will remain.

### 5. Missing values

In [63]:
# Search for - Not Disclosed
df_coffee[df_coffee.astype(str).apply(lambda x: x.str.contains('Not disclosed', case=False, na=False)).any(axis=1)]

                        coffee_name  total_score                    roaster_location   coffee_origin   roast_level price_amount        price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g      usd_per_gram
974                  Espresso Blend         94.0             New Taipei City, Taiwan   Not disclosed        Medium      NT $450         225 grams          64.0                  False                       False                    False                     False              $         gram                  TWD               NT $              450.00      14.71                g          225.0      225.00   $14.71 / 225.0g
1306  Giusto Organic Espresso Blend         94.0                 Lexington, Virginia   Not disclosed        Medium      $14.25          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               14.25      14.25               oz           12.0      340.19  $14.25 / 340.19g
1602           Twisted 4.0 Espresso         94.0                  Madison, Wisconsin   Not disclosed  Medium Light      $15.75          12 ounces          75.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.75      15.75               oz           12.0      340.19  $15.75 / 340.19g
1767               Organic Espresso         94.0               San Diego, California  Not disclosed.        Medium      $15.00          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.00      15.00               oz           12.0      340.19   $15.0 / 340.19g
1786     Golden Mean Espresso Blend         94.0           Newport Beach, California  Not disclosed.        Medium      $14.95          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               14.95      14.95               oz           12.0      340.19  $14.95 / 340.19g
1907           Twisted 3.0 Espresso         94.0                  Madison, Wisconsin  Not disclosed.        Medium      $15.75          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.75      15.75               oz           12.0      340.19  $15.75 / 340.19g
1930               Ganesha Espresso         94.0              Bellingham, Washington  Not disclosed.        Medium      $13.99          16 ounces          59.0                  False                       False                    False                     False              $        ounce                  USD                  $               13.99      13.99               oz           16.0      453.59  $13.99 / 453.59g
2008                  Bourbon Duets         94.0              Kaohsiung City, Taiwan  Not disclosed.        Medium   NTD $1,000         16 ounces          59.0                  False                       False                    False                     False              $        ounce                NTD $              NTD $                1.00        NaN               oz           16.0      453.59    $nan / 453.59g
2016            Goldilocks Espresso         94.0                    Peoria, Illinois  Not disclosed.  Medium Light      $15.00          12 ounces          75.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.00      15.00               oz           12.0      340.19   $15.0 / 340.19g
2046                Starlight Blend         96.0              Minneapolis, Minnesota  Not disclosed.        Medium      $14.99          16 ounces          67.0                  False                       False                    False                     False              $        ounce                  USD                  $               14.99      14.99               oz           16.0      453.59  $14.99 / 453.59g
2061                 Espresso Nuevo         95.0                   Ramsey, Minnesota  Not disclosed.   Medium Dark      $12.95          12 ounces          54.0                  False                       False                    False                     False              $        ounce                  USD                  $               12.95      12.95               oz           12.0      340.19  $12.95 / 340.19g
2078         Stars of Formosa Blend         94.0                      Taipei, Taiwan  Not disclosed.  Medium Light       NT$600          8 ounces          78.0                  False                       False                    False                     False            NT$        ounce                  TWD                NT$              600.00      19.61               oz            8.0      226.80   $19.61 / 226.8g
2089    Resiprocate Verita Espresso         94.0  Richmond, British Columbia, Canada  Not disclosed.   Medium Dark   CAD $44.07  1 kg. (2.2 lbs.)          49.0                  False                       False                    False                     False              $           kg                  CAD              CAD $               44.07      31.40               kg            1.0     1000.00   $31.4 / 1000.0g
2091        Stars of Italy Espresso         96.0                      Taipei, Taiwan  Not disclosed.        Medium       NT$600             8 oz.          60.0                  False                       False                    False                     False            NT$           oz                  TWD                NT$              600.00      19.61              NaN            8.0         NaN     $19.61 / nang
2127          Bonsai Blend Espresso         94.0                 Seattle, Washington  Not disclosed.   Medium Dark          NaN               NaN          47.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN       $nan / nang
2180         Natural Decaf Espresso         94.0              Minneapolis, Minnesota  Not disclosed.          Dark          NaN               NaN          44.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN       $nan / nang
2181     Decaf Organic Caffe Volcan         94.0         North Hollywood, California  Not disclosed.   Medium Dark          NaN               NaN          57.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN       $nan / nang

Looks like this phrase is only in the coffee_origin column and will convert them to NaN so keep it all clean when addressing missing values. I discovered the phrase while I was exploring and cleaning the data.

In [64]:
# Convert - Not disclosed with NaN
df_coffee['coffee_origin'] = df_coffee['coffee_origin'].replace(
    to_replace=r'(?i)^not disclosed\.?$', value=np.nan, regex=True
)

In [65]:
# Work check
# Search for - Not Disclosed
df_coffee[df_coffee.astype(str).apply(lambda x: x.str.contains('Not disclosed', case=False, na=False)).any(axis=1)]

Empty DataFrame
Columns: [coffee_name, total_score, roaster_location, coffee_origin, roast_level, price_amount, price_unit, agtron_roast, coffee_name_non_ascii, roaster_location_non_ascii, coffee_origin_non_ascii, origin_country_non_ascii, price_currency, unit_keyword, price_currency_clean, price_currency_raw, price_amount_clean, price_usd, price_unit_clean, unit_quantity, quantity_g, usd_per_gram]
Index: []

In [66]:
df_coffee.isna().sum().sort_values(ascending=False)

quantity_g                    149
price_unit_clean              149
price_usd                     141
price_currency                127
unit_keyword                  115
unit_quantity                 115
price_unit                    114
price_amount_clean            111
price_amount                  109
roast_level                    20
coffee_origin                  18
agtron_roast                    7
coffee_name                     0
total_score                     0
roaster_location                0
origin_country_non_ascii        0
coffee_name_non_ascii           0
roaster_location_non_ascii      0
coffee_origin_non_ascii         0
price_currency_raw              0
price_currency_clean            0
usd_per_gram                    0
dtype: int64

In [67]:
# Convert NaN in coffee_origin to Unknow
df_coffee['coffee_origin'] = df_coffee['coffee_origin'].fillna('Unknown')

In [68]:
# Work check
df_coffee[df_coffee.astype(str).apply(lambda x: x.str.contains('Unknown', case=False, na=False)).any(axis=1)]

                              coffee_name  total_score                    roaster_location coffee_origin   roast_level price_amount        price_unit  agtron_roast  coffee_name_non_ascii  roaster_location_non_ascii  coffee_origin_non_ascii  origin_country_non_ascii price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g      usd_per_gram
246   Colombia Los Nogales Yellow Bourbon         94.0                        Osaka, Japan       Unknown         Light      $28.00          150 grams          86.0                  False                       False                    False                     False              $         gram                  USD                  $               28.00      28.00                g          150.0      150.00    $28.0 / 150.0g
974                        Espresso Blend         94.0             New Taipei City, Taiwan       Unknown        Medium      NT $450         225 grams          64.0                  False                       False                    False                     False              $         gram                  TWD               NT $              450.00      14.71                g          225.0      225.00   $14.71 / 225.0g
1306        Giusto Organic Espresso Blend         94.0                 Lexington, Virginia       Unknown        Medium      $14.25          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               14.25      14.25               oz           12.0      340.19  $14.25 / 340.19g
1602                 Twisted 4.0 Espresso         94.0                  Madison, Wisconsin       Unknown  Medium Light      $15.75          12 ounces          75.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.75      15.75               oz           12.0      340.19  $15.75 / 340.19g
1767                     Organic Espresso         94.0               San Diego, California       Unknown        Medium      $15.00          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.00      15.00               oz           12.0      340.19   $15.0 / 340.19g
1786           Golden Mean Espresso Blend         94.0           Newport Beach, California       Unknown        Medium      $14.95          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               14.95      14.95               oz           12.0      340.19  $14.95 / 340.19g
1907                 Twisted 3.0 Espresso         94.0                  Madison, Wisconsin       Unknown        Medium      $15.75          12 ounces          60.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.75      15.75               oz           12.0      340.19  $15.75 / 340.19g
1930                     Ganesha Espresso         94.0              Bellingham, Washington       Unknown        Medium      $13.99          16 ounces          59.0                  False                       False                    False                     False              $        ounce                  USD                  $               13.99      13.99               oz           16.0      453.59  $13.99 / 453.59g
2008                        Bourbon Duets         94.0              Kaohsiung City, Taiwan       Unknown        Medium   NTD $1,000         16 ounces          59.0                  False                       False                    False                     False              $        ounce                NTD $              NTD $                1.00        NaN               oz           16.0      453.59    $nan / 453.59g
2016                  Goldilocks Espresso         94.0                    Peoria, Illinois       Unknown  Medium Light      $15.00          12 ounces          75.0                  False                       False                    False                     False              $        ounce                  USD                  $               15.00      15.00               oz           12.0      340.19   $15.0 / 340.19g
2046                      Starlight Blend         96.0              Minneapolis, Minnesota       Unknown        Medium      $14.99          16 ounces          67.0                  False                       False                    False                     False              $        ounce                  USD                  $               14.99      14.99               oz           16.0      453.59  $14.99 / 453.59g
2061                       Espresso Nuevo         95.0                   Ramsey, Minnesota       Unknown   Medium Dark      $12.95          12 ounces          54.0                  False                       False                    False                     False              $        ounce                  USD                  $               12.95      12.95               oz           12.0      340.19  $12.95 / 340.19g
2078               Stars of Formosa Blend         94.0                      Taipei, Taiwan       Unknown  Medium Light       NT$600          8 ounces          78.0                  False                       False                    False                     False            NT$        ounce                  TWD                NT$              600.00      19.61               oz            8.0      226.80   $19.61 / 226.8g
2089          Resiprocate Verita Espresso         94.0  Richmond, British Columbia, Canada       Unknown   Medium Dark   CAD $44.07  1 kg. (2.2 lbs.)          49.0                  False                       False                    False                     False              $           kg                  CAD              CAD $               44.07      31.40               kg            1.0     1000.00   $31.4 / 1000.0g
2091              Stars of Italy Espresso         96.0                      Taipei, Taiwan       Unknown        Medium       NT$600             8 oz.          60.0                  False                       False                    False                     False            NT$           oz                  TWD                NT$              600.00      19.61              NaN            8.0         NaN     $19.61 / nang
2127                Bonsai Blend Espresso         94.0                 Seattle, Washington       Unknown   Medium Dark          NaN               NaN          47.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN       $nan / nang
2180               Natural Decaf Espresso         94.0              Minneapolis, Minnesota       Unknown          Dark          NaN               NaN          44.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN       $nan / nang
2181           Decaf Organic Caffe Volcan         94.0         North Hollywood, California       Unknown   Medium Dark          NaN               NaN          57.0                  False                       False                    False                     False            NaN          NaN                  NAN                nan                 NaN        NaN              NaN            NaN         NaN       $nan / nang

I'm leaving NaN as the placeholder for missing data in numeric column types. This preserves analytical integrity by preventing skewed calculations, misleading

#### Dropped Columns Part 2

In [72]:
df_coffee.drop(columns=[
    'coffee_name_non_ascii',
    'roaster_location_non_ascii',
    'coffee_origin_non_ascii',
    'origin_country_non_ascii'
], inplace=True)

In [73]:
print(df_coffee.columns.tolist())

['coffee_name', 'total_score', 'roaster_location', 'coffee_origin', 'roast_level', 'price_amount', 'price_unit', 'agtron_roast', 'price_currency', 'unit_keyword', 'price_currency_clean', 'price_currency_raw', 'price_amount_clean', 'price_usd', 'price_unit_clean', 'unit_quantity', 'quantity_g', 'usd_per_gram']

In [75]:
df_coffee.head()

                                     coffee_name  total_score         roaster_location                             coffee_origin   roast_level price_amount price_unit  agtron_roast price_currency unit_keyword price_currency_clean price_currency_raw  price_amount_clean  price_usd price_unit_clean  unit_quantity  quantity_g     usd_per_gram
0                   Colombia Finca Campo Hermosa         94.0     Cleveland, Tennessee              Quindio Department, Colombia         Light      $29.99    8 ounces          82.0              $        ounce                  USD                  $               29.99      29.99               oz            8.0       226.8  $29.99 / 226.8g
1      Colombia Finca La Sirena Mango Co-Ferment         94.0     Cleveland, Tennessee              Quindio Department, Colombia         Light      $22.99    8 ounces          87.0              $        ounce                  USD                  $               22.99      22.99               oz            8.0       226.8  $22.99 / 226.8g
2                                       In Bloom         94.0  Jersey City, New Jersey                        Colombia; Ethiopia         Light      $25.00   250 grams          88.0              $         gram                  USD                  $               25.00      25.00                g          250.0       250.0   $25.0 / 250.0g
3  Ethiopia Washed Kaffa Gimbo Lot Rich Espresso         96.0          Chia-Yi, Taiwan           Gimbo, Kaffa Province, Ethiopia  Medium Light      NT $250   8 ounces          77.0              $        ounce                  TWD               NT $              250.00       8.17               oz            8.0       226.8   $8.17 / 226.8g
4                     Ethiopia Natural Gute Bona         95.0          Chia-Yi, Taiwan  Sidamo growing region, southern Ethiopia  Medium Light      NT $400   8 ounces          78.0              $        ounce                  TWD               NT $              400.00      13.07               oz            8.0       226.8  $13.07 / 226.8g

In [80]:
drop_cols = [
    'price_amount',
    'price_unit',
    'price_currency',
    'unit_keyword',
    'price_currency_clean',
    'price_currency_raw',
    'price_amount_clean',
    'unit_quantity',
    'price_unit_clean'
]

# Drop only those that are still present
df_coffee.drop(columns=[col for col in drop_cols if col in df_coffee.columns], inplace=True)

In [82]:
df_coffee.head()

                                     coffee_name  total_score         roaster_location                             coffee_origin   roast_level  agtron_roast  price_usd  quantity_g     usd_per_gram
0                   Colombia Finca Campo Hermosa         94.0     Cleveland, Tennessee              Quindio Department, Colombia         Light          82.0      29.99       226.8  $29.99 / 226.8g
1      Colombia Finca La Sirena Mango Co-Ferment         94.0     Cleveland, Tennessee              Quindio Department, Colombia         Light          87.0      22.99       226.8  $22.99 / 226.8g
2                                       In Bloom         94.0  Jersey City, New Jersey                        Colombia; Ethiopia         Light          88.0      25.00       250.0   $25.0 / 250.0g
3  Ethiopia Washed Kaffa Gimbo Lot Rich Espresso         96.0          Chia-Yi, Taiwan           Gimbo, Kaffa Province, Ethiopia  Medium Light          77.0       8.17       226.8   $8.17 / 226.8g
4                     Ethiopia Natural Gute Bona         95.0          Chia-Yi, Taiwan  Sidamo growing region, southern Ethiopia  Medium Light          78.0      13.07       226.8  $13.07 / 226.8g

### 6. Export

In [86]:
# Export cleaned dataset
df_coffee.to_csv(
    r"C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Top Rated Coffee\top_rated_coffee_clean.csv",
    index=False)